use dbGnosis;
go

INSERT INTO tbModulos
VALUES ('Diseños de sistemas informáticos'),
('Programación de componentes de bases de datos'),
('Desarrollo de programación orientada objetos'),
('Diseño e instalación de redes LAN'),
('Diseño de planes de negocio en asociativa cooperativa'),
('Proyecto innovador de desarrollo de portales web'),
('Diseño de arquitectura de software'),
('Conversación en inglés sobre arquitectura de software y base de datos')

INSERT INTO tbMaterias
VALUES ('Lenguaje y literatura'),
('Matemática'),
('Ciencias Naturales'),
('Estudios Sociales y Cívica'),
('Idioma Extranjero: Inglés'),
('Formación Cristiana'),
('Orientación Para la Vida'),
('Moral, Urbanidad y Cívica')
--('Educacion Física')

INSERT INTO tbSeccionAca
VALUES 
('A'),
('B'),
('C'),
('D')

INSERT INTO tbEspecialidades
VALUES ('Desarrollo de Software'),
('Diseño grafico'),
('Administrativo Contable'),
('Arquitectura'),
('Electrónica'),
('Electromecánica'),
('Mantenimiento Automotriz')

select * from tbGrados
select * from tbEspecialidades

INSERT INTO tbGrados
VALUES ('Septimo Grado', 5, 8 , 1, 1),
('Septimo Grado', 6, 8, 1, 1),
('Septimo Grado', 7, 8, 1, 1),
('Septimo Grado', 8, 8, 1, 1),
('Octavo Grado', 5, 8 , 1, 1),
('Octavo Grado', 6, 8, 1, 1),
('Octavo Grado', 7, 8, 1, 1),
('Octavo Grado', 8, 8, 1, 1),
('Noveno Grado', 5, 8 , 1, 1),
('Noveno Grado', 6, 8, 1, 1),
('Noveno Grado', 7, 8, 1, 1),
('Noveno Grado', 8, 8, 1, 1),
('Primer Año de Bachillerato', 1, 1, 1, 1), --Desarrollo de Software
('Primer Año de Bachillerato', 1, 1, 2, 1),
('Primer Año de Bachillerato', 1, 1, 1, 2),
('Primer Año de Bachillerato', 1, 1, 2, 2),
('Primer Año de Bachillerato', 2, 1, 1, 1),
('Primer Año de Bachillerato', 2, 1, 2, 1),
('Primer Año de Bachillerato', 2, 1, 1, 2),
('Primer Año de Bachillerato', 2, 1, 2, 2),
('Primer Año de Bachillerato', 3, 1, 1, 1),
('Primer Año de Bachillerato', 3, 1, 2, 1),
('Primer Año de Bachillerato', 3, 1, 1, 2),
('Primer Año de Bachillerato', 3, 1, 2, 2),
('Primer Año de Bachillerato', 4, 1, 1, 1),
('Primer Año de Bachillerato', 4, 1, 2, 1),
('Primer Año de Bachillerato', 4, 1, 1, 2),
('Primer Año de Bachillerato', 4, 1, 2, 2),  --Aqui finaliza Software
('Primer Año de Bachillerato', 1, 2, 1, 1), --Diseño Grafico
('Primer Año de Bachillerato', 1, 2, 2, 1),
('Primer Año de Bachillerato', 1, 2, 1, 2),
('Primer Año de Bachillerato', 1, 2, 2, 2),
('Primer Año de Bachillerato', 2, 2, 1, 1),
('Primer Año de Bachillerato', 2, 2, 2, 1),
('Primer Año de Bachillerato', 2, 2, 1, 2),
('Primer Año de Bachillerato', 2, 2, 2, 2),
('Primer Año de Bachillerato', 3, 2, 1, 1),
('Primer Año de Bachillerato', 3, 2, 2, 1),
('Primer Año de Bachillerato', 3, 2, 1, 2),
('Primer Año de Bachillerato', 3, 2, 2, 2),
('Primer Año de Bachillerato', 4, 2, 1, 1),
('Primer Año de Bachillerato', 4, 2, 2, 1),
('Primer Año de Bachillerato', 4, 2, 1, 2),
('Primer Año de Bachillerato', 4, 2, 2, 2), --Aqui finaliza Diseño
('Primer Año de Bachillerato', 1, 3, 1, 1), --Administrativo Contable
('Primer Año de Bachillerato', 1, 3, 2, 1),
('Primer Año de Bachillerato', 1, 3, 1, 2),
('Primer Año de Bachillerato', 1, 3, 2, 2),
('Primer Año de Bachillerato', 2, 3, 1, 1),
('Primer Año de Bachillerato', 2, 3, 2, 1),
('Primer Año de Bachillerato', 2, 3, 1, 2),
('Primer Año de Bachillerato', 2, 3, 2, 2),
('Primer Año de Bachillerato', 3, 3, 1, 1),
('Primer Año de Bachillerato', 3, 3, 2, 1),
('Primer Año de Bachillerato', 3, 3, 1, 2),
('Primer Año de Bachillerato', 3, 3, 2, 2),
('Primer Año de Bachillerato', 4, 3, 1, 1),
('Primer Año de Bachillerato', 4, 3, 2, 1),
('Primer Año de Bachillerato', 4, 3, 1, 2),
('Primer Año de Bachillerato', 4, 3, 2, 2), -- Aqui finaliza Conta
('Primer Año de Bachillerato', 1, 4, 1, 1), --Arquitectura
('Primer Año de Bachillerato', 1, 4, 2, 1),
('Primer Año de Bachillerato', 1, 4, 1, 2),
('Primer Año de Bachillerato', 1, 4, 2, 2),
('Primer Año de Bachillerato', 2, 4, 1, 1),
('Primer Año de Bachillerato', 2, 4, 2, 1),
('Primer Año de Bachillerato', 2, 4, 1, 2),
('Primer Año de Bachillerato', 2, 4, 2, 2),
('Primer Año de Bachillerato', 3, 4, 1, 1),
('Primer Año de Bachillerato', 3, 4, 2, 1),
('Primer Año de Bachillerato', 3, 4, 1, 2),
('Primer Año de Bachillerato', 3, 4, 2, 2),
('Primer Año de Bachillerato', 4, 4, 1, 1),
('Primer Año de Bachillerato', 4, 4, 2, 1),
('Primer Año de Bachillerato', 4, 4, 1, 2),
('Primer Año de Bachillerato', 4, 4, 2, 2),  --Aqui finaliza Arquitectura
('Primer Año de Bachillerato', 1, 5, 1, 1), --Electrónica
('Primer Año de Bachillerato', 1, 5, 2, 1),
('Primer Año de Bachillerato', 1, 5, 1, 2),
('Primer Año de Bachillerato', 1, 5, 2, 2),
('Primer Año de Bachillerato', 2, 5, 1, 1),
('Primer Año de Bachillerato', 2, 5, 2, 1),
('Primer Año de Bachillerato', 2, 5, 1, 2),
('Primer Año de Bachillerato', 2, 5, 2, 2),
('Primer Año de Bachillerato', 3, 5, 1, 1),
('Primer Año de Bachillerato', 3, 5, 2, 1),
('Primer Año de Bachillerato', 3, 5, 1, 2),
('Primer Año de Bachillerato', 3, 5, 2, 2),
('Primer Año de Bachillerato', 4, 5, 1, 1),
('Primer Año de Bachillerato', 4, 5, 2, 1),
('Primer Año de Bachillerato', 4, 5, 1, 2),
('Primer Año de Bachillerato', 4, 5, 2, 2),  --Aqui finaliza Electrónica
('Primer Año de Bachillerato', 1, 5, 1, 1), --Electromecánica
('Primer Año de Bachillerato', 1, 5, 2, 1),
('Primer Año de Bachillerato', 1, 5, 1, 2),
('Primer Año de Bachillerato', 1, 5, 2, 2),
('Primer Año de Bachillerato', 2, 5, 1, 1),
('Primer Año de Bachillerato', 2, 5, 2, 1),
('Primer Año de Bachillerato', 2, 5, 1, 2),
('Primer Año de Bachillerato', 2, 5, 2, 2),
('Primer Año de Bachillerato', 3, 5, 1, 1),
('Primer Año de Bachillerato', 3, 5, 2, 1),
('Primer Año de Bachillerato', 3, 5, 1, 2),
('Primer Año de Bachillerato', 3, 5, 2, 2),
('Primer Año de Bachillerato', 4, 5, 1, 1),
('Primer Año de Bachillerato', 4, 5, 2, 1),
('Primer Año de Bachillerato', 4, 5, 1, 2),
('Primer Año de Bachillerato', 4, 5, 2, 2), --Aqui finazila Electromecánica
('Primer Año de Bachillerato', 1, 5, 1, 1), --Mantenimiento Automotriz
('Primer Año de Bachillerato', 1, 5, 2, 1),
('Primer Año de Bachillerato', 1, 5, 1, 2),
('Primer Año de Bachillerato', 1, 5, 2, 2),
('Primer Año de Bachillerato', 2, 5, 1, 1),
('Primer Año de Bachillerato', 2, 5, 2, 1),
('Primer Año de Bachillerato', 2, 5, 1, 2),
('Primer Año de Bachillerato', 2, 5, 2, 2),
('Primer Año de Bachillerato', 3, 5, 1, 1),
('Primer Año de Bachillerato', 3, 5, 2, 1),
('Primer Año de Bachillerato', 3, 5, 1, 2),
('Primer Año de Bachillerato', 3, 5, 2, 2),
('Primer Año de Bachillerato', 4, 5, 1, 1),
('Primer Año de Bachillerato', 4, 5, 2, 1),
('Primer Año de Bachillerato', 4, 5, 1, 2),
('Primer Año de Bachillerato', 4, 5, 2, 2), --Aqui finazila Mantenimiento Automotriz
('Segundo Año de Bachillerato', 1, 1, 1, 1), --Desarrollo de Software
('Segundo Año de Bachillerato', 1, 1, 2, 1),
('Segundo Año de Bachillerato', 1, 1, 1, 2),
('Segundo Año de Bachillerato', 1, 1, 2, 2),
('Segundo Año de Bachillerato', 2, 1, 1, 1),
('Segundo Año de Bachillerato', 2, 1, 2, 1),
('Segundo Año de Bachillerato', 2, 1, 1, 2),
('Segundo Año de Bachillerato', 2, 1, 2, 2),
('Segundo Año de Bachillerato', 3, 1, 1, 1),
('Segundo Año de Bachillerato', 3, 1, 2, 1),
('Segundo Año de Bachillerato', 3, 1, 1, 2),
('Segundo Año de Bachillerato', 3, 1, 2, 2),
('Segundo Año de Bachillerato', 4, 1, 1, 1),
('Segundo Año de Bachillerato', 4, 1, 2, 1),
('Segundo Año de Bachillerato', 4, 1, 1, 2),
('Segundo Año de Bachillerato', 4, 1, 2, 2),  --Aqui finaliza Software
('Segundo Año de Bachillerato', 1, 2, 1, 1), --Diseño Grafico
('Segundo Año de Bachillerato', 1, 2, 2, 1),
('Segundo Año de Bachillerato', 1, 2, 1, 2),
('Segundo Año de Bachillerato', 1, 2, 2, 2),
('Segundo Año de Bachillerato', 2, 2, 1, 1),
('Segundo Año de Bachillerato', 2, 2, 2, 1),
('Segundo Año de Bachillerato', 2, 2, 1, 2),
('Segundo Año de Bachillerato', 2, 2, 2, 2),
('Segundo Año de Bachillerato', 3, 2, 1, 1),
('Segundo Año de Bachillerato', 3, 2, 2, 1),
('Segundo Año de Bachillerato', 3, 2, 1, 2),
('Segundo Año de Bachillerato', 3, 2, 2, 2),
('Segundo Año de Bachillerato', 4, 2, 1, 1),
('Segundo Año de Bachillerato', 4, 2, 2, 1),
('Segundo Año de Bachillerato', 4, 2, 1, 2),
('Segundo Año de Bachillerato', 4, 2, 2, 2), --Aqui finaliza Diseño
('Segundo Año de Bachillerato', 1, 3, 1, 1), --Administrativo Contable
('Segundo Año de Bachillerato', 1, 3, 2, 1),
('Segundo Año de Bachillerato', 1, 3, 1, 2),
('Segundo Año de Bachillerato', 1, 3, 2, 2),
('Segundo Año de Bachillerato', 2, 3, 1, 1),
('Segundo Año de Bachillerato', 2, 3, 2, 1),
('Segundo Año de Bachillerato', 2, 3, 1, 2),
('Segundo Año de Bachillerato', 2, 3, 2, 2),
('Segundo Año de Bachillerato', 3, 3, 1, 1),
('Segundo Año de Bachillerato', 3, 3, 2, 1),
('Segundo Año de Bachillerato', 3, 3, 1, 2),
('Segundo Año de Bachillerato', 3, 3, 2, 2),
('Segundo Año de Bachillerato', 4, 3, 1, 1),
('Segundo Año de Bachillerato', 4, 3, 2, 1),
('Segundo Año de Bachillerato', 4, 3, 1, 2),
('Segundo Año de Bachillerato', 4, 3, 2, 2), -- Aqui finaliza Conta
('Segundo Año de Bachillerato', 1, 4, 1, 1), --Arquitectura
('Segundo Año de Bachillerato', 1, 4, 2, 1),
('Segundo Año de Bachillerato', 1, 4, 1, 2),
('Segundo Año de Bachillerato', 1, 4, 2, 2),
('Segundo Año de Bachillerato', 2, 4, 1, 1),
('Segundo Año de Bachillerato', 2, 4, 2, 1),
('Segundo Año de Bachillerato', 2, 4, 1, 2),
('Segundo Año de Bachillerato', 2, 4, 2, 2),
('Segundo Año de Bachillerato', 3, 4, 1, 1),
('Segundo Año de Bachillerato', 3, 4, 2, 1),
('Segundo Año de Bachillerato', 3, 4, 1, 2),
('Segundo Año de Bachillerato', 3, 4, 2, 2),
('Segundo Año de Bachillerato', 4, 4, 1, 1),
('Segundo Año de Bachillerato', 4, 4, 2, 1),
('Segundo Año de Bachillerato', 4, 4, 1, 2),
('Segundo Año de Bachillerato', 4, 4, 2, 2),  --Aqui finaliza Arquitectura
('Segundo Año de Bachillerato', 1, 5, 1, 1), --Electrónica
('Segundo Año de Bachillerato', 1, 5, 2, 1),
('Segundo Año de Bachillerato', 1, 5, 1, 2),
('Segundo Año de Bachillerato', 1, 5, 2, 2),
('Segundo Año de Bachillerato', 2, 5, 1, 1),
('Segundo Año de Bachillerato', 2, 5, 2, 1),
('Segundo Año de Bachillerato', 2, 5, 1, 2),
('Segundo Año de Bachillerato', 2, 5, 2, 2),
('Segundo Año de Bachillerato', 3, 5, 1, 1),
('Segundo Año de Bachillerato', 3, 5, 2, 1),
('Segundo Año de Bachillerato', 3, 5, 1, 2),
('Segundo Año de Bachillerato', 3, 5, 2, 2),
('Segundo Año de Bachillerato', 4, 5, 1, 1),
('Segundo Año de Bachillerato', 4, 5, 2, 1),
('Segundo Año de Bachillerato', 4, 5, 1, 2),
('Segundo Año de Bachillerato', 4, 5, 2, 2),  --Aqui finaliza Electrónica
('Segundo Año de Bachillerato', 1, 5, 1, 1), --Electromecánica
('Segundo Año de Bachillerato', 1, 5, 2, 1),
('Segundo Año de Bachillerato', 1, 5, 1, 2),
('Segundo Año de Bachillerato', 1, 5, 2, 2),
('Segundo Año de Bachillerato', 2, 5, 1, 1),
('Segundo Año de Bachillerato', 2, 5, 2, 1),
('Segundo Año de Bachillerato', 2, 5, 1, 2),
('Segundo Año de Bachillerato', 2, 5, 2, 2),
('Segundo Año de Bachillerato', 3, 5, 1, 1),
('Segundo Año de Bachillerato', 3, 5, 2, 1),
('Segundo Año de Bachillerato', 3, 5, 1, 2),
('Segundo Año de Bachillerato', 3, 5, 2, 2),
('Segundo Año de Bachillerato', 4, 5, 1, 1),
('Segundo Año de Bachillerato', 4, 5, 2, 1),
('Segundo Año de Bachillerato', 4, 5, 1, 2),
('Segundo Año de Bachillerato', 4, 5, 2, 2), --Aqui finazila Electromecánica
('Segundo Año de Bachillerato', 1, 5, 1, 1), --Mantenimiento Automotriz
('Segundo Año de Bachillerato', 1, 5, 2, 1),
('Segundo Año de Bachillerato', 1, 5, 1, 2),
('Segundo Año de Bachillerato', 1, 5, 2, 2),
('Segundo Año de Bachillerato', 2, 5, 1, 1),
('Segundo Año de Bachillerato', 2, 5, 2, 1),
('Segundo Año de Bachillerato', 2, 5, 1, 2),
('Segundo Año de Bachillerato', 2, 5, 2, 2),
('Segundo Año de Bachillerato', 3, 5, 1, 1),
('Segundo Año de Bachillerato', 3, 5, 2, 1),
('Segundo Año de Bachillerato', 3, 5, 1, 2),
('Segundo Año de Bachillerato', 3, 5, 2, 2),
('Segundo Año de Bachillerato', 4, 5, 1, 1),
('Segundo Año de Bachillerato', 4, 5, 2, 1),
('Segundo Año de Bachillerato', 4, 5, 1, 2),
('Segundo Año de Bachillerato', 4, 5, 2, 2), --Aqui finazila Mantenimiento Automotriz
('Tercer Año de Bachillerato', 1, 1, 1, 1), --Desarrollo de Software
('Tercer Año de Bachillerato', 1, 1, 2, 1),
('Tercer Año de Bachillerato', 1, 1, 1, 2),
('Tercer Año de Bachillerato', 1, 1, 2, 2),
('Tercer Año de Bachillerato', 2, 1, 1, 1),
('Tercer Año de Bachillerato', 2, 1, 2, 1),
('Tercer Año de Bachillerato', 2, 1, 1, 2),
('Tercer Año de Bachillerato', 2, 1, 2, 2),
('Tercer Año de Bachillerato', 3, 1, 1, 1),
('Tercer Año de Bachillerato', 3, 1, 2, 1),
('Tercer Año de Bachillerato', 3, 1, 1, 2),
('Tercer Año de Bachillerato', 3, 1, 2, 2),
('Tercer Año de Bachillerato', 4, 1, 1, 1),
('Tercer Año de Bachillerato', 4, 1, 2, 1),
('Tercer Año de Bachillerato', 4, 1, 1, 2),
('Tercer Año de Bachillerato', 4, 1, 2, 2),  --Aqui finaliza Software
('Tercer Año de Bachillerato', 1, 2, 1, 1), --Diseño Grafico
('Tercer Año de Bachillerato', 1, 2, 2, 1),
('Tercer Año de Bachillerato', 1, 2, 1, 2),
('Tercer Año de Bachillerato', 1, 2, 2, 2),
('Tercer Año de Bachillerato', 2, 2, 1, 1),
('Tercer Año de Bachillerato', 2, 2, 2, 1),
('Tercer Año de Bachillerato', 2, 2, 1, 2),
('Tercer Año de Bachillerato', 2, 2, 2, 2),
('Tercer Año de Bachillerato', 3, 2, 1, 1),
('Tercer Año de Bachillerato', 3, 2, 2, 1),
('Tercer Año de Bachillerato', 3, 2, 1, 2),
('Tercer Año de Bachillerato', 3, 2, 2, 2),
('Tercer Año de Bachillerato', 4, 2, 1, 1),
('Tercer Año de Bachillerato', 4, 2, 2, 1),
('Tercer Año de Bachillerato', 4, 2, 1, 2),
('Tercer Año de Bachillerato', 4, 2, 2, 2), --Aqui finaliza Diseño
('Tercer Año de Bachillerato', 1, 3, 1, 1), --Administrativo Contable
('Tercer Año de Bachillerato', 1, 3, 2, 1),
('Tercer Año de Bachillerato', 1, 3, 1, 2),
('Tercer Año de Bachillerato', 1, 3, 2, 2),
('Tercer Año de Bachillerato', 2, 3, 1, 1),
('Tercer Año de Bachillerato', 2, 3, 2, 1),
('Tercer Año de Bachillerato', 2, 3, 1, 2),
('Tercer Año de Bachillerato', 2, 3, 2, 2),
('Tercer Año de Bachillerato', 3, 3, 1, 1),
('Tercer Año de Bachillerato', 3, 3, 2, 1),
('Tercer Año de Bachillerato', 3, 3, 1, 2),
('Tercer Año de Bachillerato', 3, 3, 2, 2),
('Tercer Año de Bachillerato', 4, 3, 1, 1),
('Tercer Año de Bachillerato', 4, 3, 2, 1),
('Tercer Año de Bachillerato', 4, 3, 1, 2),
('Tercer Año de Bachillerato', 4, 3, 2, 2), -- Aqui finaliza Conta
('Tercer Año de Bachillerato', 1, 4, 1, 1), --Arquitectura
('Tercer Año de Bachillerato', 1, 4, 2, 1),
('Tercer Año de Bachillerato', 1, 4, 1, 2),
('Tercer Año de Bachillerato', 1, 4, 2, 2),
('Tercer Año de Bachillerato', 2, 4, 1, 1),
('Tercer Año de Bachillerato', 2, 4, 2, 1),
('Tercer Año de Bachillerato', 2, 4, 1, 2),
('Tercer Año de Bachillerato', 2, 4, 2, 2),
('Tercer Año de Bachillerato', 3, 4, 1, 1),
('Tercer Año de Bachillerato', 3, 4, 2, 1),
('Tercer Año de Bachillerato', 3, 4, 1, 2),
('Tercer Año de Bachillerato', 3, 4, 2, 2),
('Tercer Año de Bachillerato', 4, 4, 1, 1),
('Tercer Año de Bachillerato', 4, 4, 2, 1),
('Tercer Año de Bachillerato', 4, 4, 1, 2),
('Tercer Año de Bachillerato', 4, 4, 2, 2),  --Aqui finaliza Arquitectura
('Tercer Año de Bachillerato', 1, 5, 1, 1), --Electrónica
('Tercer Año de Bachillerato', 1, 5, 2, 1),
('Tercer Año de Bachillerato', 1, 5, 1, 2),
('Tercer Año de Bachillerato', 1, 5, 2, 2),
('Tercer Año de Bachillerato', 2, 5, 1, 1),
('Tercer Año de Bachillerato', 2, 5, 2, 1),
('Tercer Año de Bachillerato', 2, 5, 1, 2),
('Tercer Año de Bachillerato', 2, 5, 2, 2),
('Tercer Año de Bachillerato', 3, 5, 1, 1),
('Tercer Año de Bachillerato', 3, 5, 2, 1),
('Tercer Año de Bachillerato', 3, 5, 1, 2),
('Tercer Año de Bachillerato', 3, 5, 2, 2),
('Tercer Año de Bachillerato', 4, 5, 1, 1),
('Tercer Año de Bachillerato', 4, 5, 2, 1),
('Tercer Año de Bachillerato', 4, 5, 1, 2),
('Tercer Año de Bachillerato', 4, 5, 2, 2),  --Aqui finaliza Electrónica
('Tercer Año de Bachillerato', 1, 5, 1, 1), --Electromecánica
('Tercer Año de Bachillerato', 1, 5, 2, 1),
('Tercer Año de Bachillerato', 1, 5, 1, 2),
('Tercer Año de Bachillerato', 1, 5, 2, 2),
('Tercer Año de Bachillerato', 2, 5, 1, 1),
('Tercer Año de Bachillerato', 2, 5, 2, 1),
('Tercer Año de Bachillerato', 2, 5, 1, 2),
('Tercer Año de Bachillerato', 2, 5, 2, 2),
('Tercer Año de Bachillerato', 3, 5, 1, 1),
('Tercer Año de Bachillerato', 3, 5, 2, 1),
('Tercer Año de Bachillerato', 3, 5, 1, 2),
('Tercer Año de Bachillerato', 3, 5, 2, 2),
('Tercer Año de Bachillerato', 4, 5, 1, 1),
('Tercer Año de Bachillerato', 4, 5, 2, 1),
('Tercer Año de Bachillerato', 4, 5, 1, 2),
('Tercer Año de Bachillerato', 4, 5, 2, 2), --Aqui finazila Electromecánica
('Tercer Año de Bachillerato', 1, 5, 1, 1), --Mantenimiento Automotriz
('Tercer Año de Bachillerato', 1, 5, 2, 1),
('Tercer Año de Bachillerato', 1, 5, 1, 2),
('Tercer Año de Bachillerato', 1, 5, 2, 2),
('Tercer Año de Bachillerato', 2, 5, 1, 1),
('Tercer Año de Bachillerato', 2, 5, 2, 1),
('Tercer Año de Bachillerato', 2, 5, 1, 2),
('Tercer Año de Bachillerato', 2, 5, 2, 2),
('Tercer Año de Bachillerato', 3, 5, 1, 1),
('Tercer Año de Bachillerato', 3, 5, 2, 1),
('Tercer Año de Bachillerato', 3, 5, 1, 2),
('Tercer Año de Bachillerato', 3, 5, 2, 2),
('Tercer Año de Bachillerato', 4, 5, 1, 1),
('Tercer Año de Bachillerato', 4, 5, 2, 1),
('Tercer Año de Bachillerato', 4, 5, 1, 2),
('Tercer Año de Bachillerato', 4, 5, 2, 2) --Aqui finazila Mantenimiento Automotriz