/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gnosis.system;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class frmBlocMateria extends javax.swing.JFrame {

    /**
     * Creates new form frmBlocMateria
     */
    String fontFamily, fontSize, fontStyle;
    Font newFont;
    int fstyle;
    int fsize = 12;
    int[] stylevalue = {Font.PLAIN, Font.BOLD, Font.ITALIC};
    JList fontFamilyList, fontStyleList, fontSizeList;
    String[] fontStyleValues = {"PLAIN", "BOLD", "ITALIC"};
     
     
    public frmBlocMateria() {
        initComponents();

    }
    
    public frmBlocMateria(int idalumno, String materiamodulo, String contenido){
        initComponents();
        MateriaColor(materiamodulo);
        lblPortafolio.setText("Portafolios > " + materiamodulo);
    }
    
    final void GuardarArchivoTXT(){
            final JFileChooser SaveAs = new JFileChooser();
            SaveAs.setApproveButtonText("Save");
            //Opening the dialog and asking from user where to save the file.
            int actionDialog = SaveAs.showOpenDialog(this);
            if (actionDialog != JFileChooser.APPROVE_OPTION) {
                return;
            }
            File fileName = new File(SaveAs.getSelectedFile() + ".txt");
            BufferedWriter outFile = null;
            try {
                outFile = new BufferedWriter(new FileWriter(fileName));
                area.write(outFile);
            } catch (IOException e) {
                e.printStackTrace();
            }
    }
    
void MateriaColor(String materiamodulo){
        Color mainColor;
        Color secondColor;
        Color fontColor;
        
        switch (materiamodulo) {
            case "Sociales":
                mainColor = new Color(98, 148, 244);
                secondColor = new Color(149, 184, 252);
                fontColor = new Color(32,32,32);
                break;
            case "Matemáticas":
                mainColor = new Color(255, 153, 0);
                secondColor = new Color(255, 182, 73);
                fontColor = new Color(32,32,32);
                break;
            case "Ingles":
                mainColor = new Color(255, 189, 62);
                secondColor = new Color(255, 198, 87);
                fontColor = new Color(32,32,32);
                break;
            case "Ciencias":
                mainColor = new Color(127, 211, 106);
                secondColor = new Color(152, 215, 136);
                fontColor = new Color(32,32,32);
                break;
            case "Lenguaje":
                mainColor = new Color(227, 63, 63);
                secondColor = new Color(231, 87, 87);
                fontColor = new Color(255,255,255);
                break;
            default:
                mainColor = new Color(32,32,32);
                secondColor = new Color(90,90,90);
                fontColor = new Color(255,255,255);
                break;
        }
        namePan.setBackground(mainColor);
        lblPortafolio.setForeground(fontColor);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        namePan = new customizeObjects.PanelRound();
        lblPortafolio = new javax.swing.JLabel();
        buttonRound1 = new customizeObjects.ButtonRound();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        buttonRound3 = new customizeObjects.ButtonRound();
        buttonRound4 = new customizeObjects.ButtonRound();
        buttonRound5 = new customizeObjects.ButtonRound();
        buttonRound6 = new customizeObjects.ButtonRound();
        buttonRound7 = new customizeObjects.ButtonRound();
        buttonRound8 = new customizeObjects.ButtonRound();
        buttonRound9 = new customizeObjects.ButtonRound();
        buttonRound10 = new customizeObjects.ButtonRound();
        buttonRound11 = new customizeObjects.ButtonRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonRound13 = new customizeObjects.ButtonRound();
        buttonRound14 = new customizeObjects.ButtonRound();
        buttonRound15 = new customizeObjects.ButtonRound();
        buttonRound16 = new customizeObjects.ButtonRound();
        buttonRound17 = new customizeObjects.ButtonRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonRound12 = new customizeObjects.ButtonRound();
        buttonRound18 = new customizeObjects.ButtonRound();
        btnGuardar = new customizeObjects.ButtonRound();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        panelRound1 = new customizeObjects.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        panelRound5 = new customizeObjects.PanelRound();
        panelRound6 = new customizeObjects.PanelRound();
        panelRound3 = new customizeObjects.PanelRound();
        panelRound4 = new customizeObjects.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 32, 32));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(32, 32, 32));
        jPanel2.setPreferredSize(new java.awt.Dimension(775, 50));
        jPanel2.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel4.setBackground(new java.awt.Color(32, 32, 32));
        jPanel4.setPreferredSize(new java.awt.Dimension(775, 40));

        namePan.setBackground(new java.awt.Color(90, 90, 90));
        namePan.setRoundBottomLeft(25);
        namePan.setRoundBottomRight(25);
        namePan.setRoundTopLeft(25);
        namePan.setRoundTopRight(25);

        lblPortafolio.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        lblPortafolio.setForeground(new java.awt.Color(255, 255, 255));
        lblPortafolio.setText("Nombre del Portafolio Sociales");

        javax.swing.GroupLayout namePanLayout = new javax.swing.GroupLayout(namePan);
        namePan.setLayout(namePanLayout);
        namePanLayout.setHorizontalGroup(
            namePanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblPortafolio, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namePanLayout.setVerticalGroup(
            namePanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPortafolio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonRound1.setText("buttonRound1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namePan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(buttonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 711, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namePan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(32, 32, 32));
        jPanel5.setPreferredSize(new java.awt.Dimension(10, 405));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel6.setBackground(new java.awt.Color(32, 32, 32));
        jPanel6.setRequestFocusEnabled(false);

        buttonRound3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/textalign-left.png"))); // NOI18N
        buttonRound3.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound3.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);

        buttonRound4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/textalign-center.png"))); // NOI18N
        buttonRound4.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound4.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);

        buttonRound5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/textalign-right.png"))); // NOI18N
        buttonRound5.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound5.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);

        buttonRound6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/text-bold.png"))); // NOI18N
        buttonRound6.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound6.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        buttonRound6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound6ActionPerformed(evt);
            }
        });

        buttonRound7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/text-underline.png"))); // NOI18N
        buttonRound7.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound7.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);

        buttonRound8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/text-italic.png"))); // NOI18N
        buttonRound8.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound8.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);

        buttonRound9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/task.png"))); // NOI18N
        buttonRound9.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound9.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);

        buttonRound10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/link-x21.png"))); // NOI18N
        buttonRound10.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound10.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);

        buttonRound11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/paint.png"))); // NOI18N
        buttonRound11.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound11.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Text.");

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Headings.");

        buttonRound13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/h1.png"))); // NOI18N
        buttonRound13.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound13.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);

        buttonRound14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/h2.png"))); // NOI18N
        buttonRound14.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound14.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);

        buttonRound15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/h3.png"))); // NOI18N
        buttonRound15.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound15.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);

        buttonRound16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/receive-square-white.png"))); // NOI18N
        buttonRound16.setPreferredSize(new java.awt.Dimension(114, 35));
        buttonRound16.setRound(20);
        buttonRound16.setStyle(customizeObjects.ButtonRound.ButtonStyle.ROJO);

        buttonRound17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/receive-square.png"))); // NOI18N
        buttonRound17.setPreferredSize(new java.awt.Dimension(114, 35));
        buttonRound17.setRound(20);
        buttonRound17.setStyle(customizeObjects.ButtonRound.ButtonStyle.SOCIALES);

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Exportar en .PDF");

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Exportar en .DOCX");

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Theme.");

        buttonRound12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/moon.png"))); // NOI18N
        buttonRound12.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound12.setStyle(customizeObjects.ButtonRound.ButtonStyle.SOCIALES);

        buttonRound18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sun.png"))); // NOI18N
        buttonRound18.setToolTipText("");
        buttonRound18.setPreferredSize(new java.awt.Dimension(40, 40));
        buttonRound18.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/folder-add.png"))); // NOI18N
        btnGuardar.setPreferredSize(new java.awt.Dimension(62, 35));
        btnGuardar.setRound(20);
        btnGuardar.setStyle(customizeObjects.ButtonRound.ButtonStyle.VERDE);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Guardar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(buttonRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(buttonRound7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(buttonRound8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(buttonRound9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(buttonRound10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(buttonRound11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(buttonRound13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonRound14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(buttonRound15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(buttonRound12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonRound18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(buttonRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(buttonRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(buttonRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonRound17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonRound16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRound7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRound8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRound9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRound10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRound11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRound13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRound14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRound15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRound12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRound18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRound16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRound17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.EAST);

        jPanel7.setBackground(new java.awt.Color(32, 32, 32));
        jPanel7.setPreferredSize(new java.awt.Dimension(780, 10));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        panelRound1.setBackground(java.awt.Color.white);
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        area.setBackground(new java.awt.Color(255, 255, 255));
        area.setColumns(20);
        area.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        area.setForeground(new java.awt.Color(32, 32, 32));
        area.setLineWrap(true);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        panelRound1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setPreferredSize(new java.awt.Dimension(10, 522));

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        panelRound1.add(panelRound5, java.awt.BorderLayout.LINE_END);

        panelRound6.setBackground(new java.awt.Color(255, 255, 255));
        panelRound6.setPreferredSize(new java.awt.Dimension(10, 522));

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        panelRound1.add(panelRound6, java.awt.BorderLayout.LINE_START);

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setPreferredSize(new java.awt.Dimension(644, 10));
        panelRound3.setRoundTopLeft(15);
        panelRound3.setRoundTopRight(15);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelRound1.add(panelRound3, java.awt.BorderLayout.NORTH);

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setPreferredSize(new java.awt.Dimension(644, 10));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelRound1.add(panelRound4, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(panelRound1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    
    private void buttonRound6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound6ActionPerformed
        // TODO add your handling code here:
        fontStyleList = new JList(fontStyleValues);
        newFont = new Font("Poppins", 3, 12);
        area.setFont(newFont);
    }//GEN-LAST:event_buttonRound6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        customization.mainUtilities();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBlocMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private customizeObjects.ButtonRound btnGuardar;
    private customizeObjects.ButtonRound buttonRound1;
    private customizeObjects.ButtonRound buttonRound10;
    private customizeObjects.ButtonRound buttonRound11;
    private customizeObjects.ButtonRound buttonRound12;
    private customizeObjects.ButtonRound buttonRound13;
    private customizeObjects.ButtonRound buttonRound14;
    private customizeObjects.ButtonRound buttonRound15;
    private customizeObjects.ButtonRound buttonRound16;
    private customizeObjects.ButtonRound buttonRound17;
    private customizeObjects.ButtonRound buttonRound18;
    private customizeObjects.ButtonRound buttonRound3;
    private customizeObjects.ButtonRound buttonRound4;
    private customizeObjects.ButtonRound buttonRound5;
    private customizeObjects.ButtonRound buttonRound6;
    private customizeObjects.ButtonRound buttonRound7;
    private customizeObjects.ButtonRound buttonRound8;
    private customizeObjects.ButtonRound buttonRound9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPortafolio;
    private customizeObjects.PanelRound namePan;
    private customizeObjects.PanelRound panelRound1;
    private customizeObjects.PanelRound panelRound3;
    private customizeObjects.PanelRound panelRound4;
    private customizeObjects.PanelRound panelRound5;
    private customizeObjects.PanelRound panelRound6;
    // End of variables declaration//GEN-END:variables
}
