/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gnosis.system;

import java.awt.Component;
import java.util.Calendar;

/**
 *
 * @author santi
 */
public class panDate extends javax.swing.JPanel {

    /**
     * Creates new form panDate
     */
    private int month;
    private int year;
    
    public panDate(int month, int year) {
        initComponents();
        this.month = month;
        this.year = year;
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void init(){
        lunes.asTitle();
        martes.asTitle();
        miercoles.asTitle();
        jueves.asTitle();
        viernes.asTitle();
        sabado.asTitle();
        domingo.asTitle();
        setDate();
    }
    
    private void setDate(){
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.MONTH, month -1); //month index starts in 0
        calendar.set(Calendar.DATE, 1);
        int startDay = calendar.get(Calendar.DAY_OF_WEEK) -1;
        calendar.add(Calendar.DATE, -startDay);
        for (Component com:getComponents()) {
            Cell cell = (Cell) com;
            if (!cell.isTitle()) {
                cell.setText(calendar.get(Calendar.DATE)+ "");
                cell.setDate(calendar.getTime());
                cell.currentMonth(calendar.get(Calendar.MONTH) == month - 1);
                calendar.add(Calendar.DATE, 1);
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        domingo = new gnosis.system.Cell();
        lunes = new gnosis.system.Cell();
        martes = new gnosis.system.Cell();
        miercoles = new gnosis.system.Cell();
        jueves = new gnosis.system.Cell();
        viernes = new gnosis.system.Cell();
        sabado = new gnosis.system.Cell();
        cell8 = new gnosis.system.Cell();
        cell9 = new gnosis.system.Cell();
        cell10 = new gnosis.system.Cell();
        cell11 = new gnosis.system.Cell();
        cell12 = new gnosis.system.Cell();
        cell13 = new gnosis.system.Cell();
        cell14 = new gnosis.system.Cell();
        cell15 = new gnosis.system.Cell();
        cell16 = new gnosis.system.Cell();
        cell17 = new gnosis.system.Cell();
        cell18 = new gnosis.system.Cell();
        cell19 = new gnosis.system.Cell();
        cell20 = new gnosis.system.Cell();
        cell21 = new gnosis.system.Cell();
        cell22 = new gnosis.system.Cell();
        cell23 = new gnosis.system.Cell();
        cell24 = new gnosis.system.Cell();
        cell25 = new gnosis.system.Cell();
        cell26 = new gnosis.system.Cell();
        cell27 = new gnosis.system.Cell();
        cell28 = new gnosis.system.Cell();
        cell29 = new gnosis.system.Cell();
        cell30 = new gnosis.system.Cell();
        cell31 = new gnosis.system.Cell();
        cell32 = new gnosis.system.Cell();
        cell33 = new gnosis.system.Cell();
        cell34 = new gnosis.system.Cell();
        cell35 = new gnosis.system.Cell();
        cell36 = new gnosis.system.Cell();
        cell37 = new gnosis.system.Cell();
        cell38 = new gnosis.system.Cell();
        cell39 = new gnosis.system.Cell();
        cell40 = new gnosis.system.Cell();
        cell41 = new gnosis.system.Cell();
        cell42 = new gnosis.system.Cell();
        cell43 = new gnosis.system.Cell();
        cell44 = new gnosis.system.Cell();
        cell45 = new gnosis.system.Cell();
        cell46 = new gnosis.system.Cell();
        cell47 = new gnosis.system.Cell();
        cell48 = new gnosis.system.Cell();
        cell49 = new gnosis.system.Cell();

        setLayout(new java.awt.GridLayout(7, 7));

        domingo.setText("Dom");
        domingo.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(domingo);

        lunes.setText("Lun");
        lunes.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        lunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunesActionPerformed(evt);
            }
        });
        add(lunes);

        martes.setText("Mar");
        martes.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(martes);

        miercoles.setText("Mier");
        miercoles.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(miercoles);

        jueves.setText("Jue");
        jueves.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(jueves);

        viernes.setText("Vie");
        viernes.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(viernes);

        sabado.setText("Sab");
        sabado.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(sabado);

        cell8.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell8.setRound(20);
        cell8.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell8);

        cell9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell9.setRound(20);
        cell9.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell9);

        cell10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell10.setRound(20);
        cell10.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell10);

        cell11.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell11.setRound(20);
        cell11.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell11);

        cell12.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell12.setRound(20);
        cell12.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell12);

        cell13.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell13.setRound(20);
        cell13.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell13);

        cell14.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell14.setRound(20);
        cell14.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell14);

        cell15.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell15.setRound(20);
        cell15.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell15);

        cell16.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell16.setRound(20);
        cell16.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell16);

        cell17.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell17.setRound(20);
        cell17.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell17);

        cell18.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell18.setRound(20);
        cell18.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell18);

        cell19.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell19.setRound(20);
        cell19.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell19);

        cell20.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell20.setRound(20);
        cell20.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell20);

        cell21.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell21.setRound(20);
        cell21.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell21);

        cell22.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell22.setRound(20);
        cell22.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell22);

        cell23.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell23.setRound(20);
        cell23.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell23);

        cell24.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell24.setRound(20);
        cell24.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell24);

        cell25.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell25.setRound(20);
        cell25.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell25);

        cell26.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell26.setRound(20);
        cell26.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell26);

        cell27.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell27.setRound(20);
        cell27.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell27);

        cell28.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell28.setRound(20);
        cell28.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell28);

        cell29.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell29.setRound(20);
        cell29.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell29);

        cell30.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell30.setRound(20);
        cell30.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell30);

        cell31.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell31.setRound(20);
        cell31.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell31);

        cell32.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell32.setRound(20);
        cell32.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell32);

        cell33.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell33.setRound(20);
        cell33.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell33);

        cell34.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell34.setRound(20);
        cell34.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell34);

        cell35.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell35.setRound(20);
        cell35.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell35);

        cell36.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell36.setRound(20);
        cell36.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell36);

        cell37.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell37.setRound(20);
        cell37.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell37);

        cell38.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell38.setRound(20);
        cell38.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell38);

        cell39.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell39.setRound(20);
        cell39.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell39);

        cell40.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell40.setRound(20);
        cell40.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell40);

        cell41.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell41.setRound(20);
        cell41.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell41);

        cell42.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell42.setRound(20);
        cell42.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell42);

        cell43.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell43.setRound(20);
        cell43.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell43);

        cell44.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell44.setRound(20);
        cell44.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell44);

        cell45.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell45.setRound(20);
        cell45.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell45);

        cell46.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell46.setRound(20);
        cell46.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell46);

        cell47.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell47.setRound(20);
        cell47.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell47);

        cell48.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell48.setRound(20);
        cell48.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell48);

        cell49.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cell49.setRound(20);
        cell49.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        add(cell49);
    }// </editor-fold>//GEN-END:initComponents

    private void lunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lunesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gnosis.system.Cell cell10;
    private gnosis.system.Cell cell11;
    private gnosis.system.Cell cell12;
    private gnosis.system.Cell cell13;
    private gnosis.system.Cell cell14;
    private gnosis.system.Cell cell15;
    private gnosis.system.Cell cell16;
    private gnosis.system.Cell cell17;
    private gnosis.system.Cell cell18;
    private gnosis.system.Cell cell19;
    private gnosis.system.Cell cell20;
    private gnosis.system.Cell cell21;
    private gnosis.system.Cell cell22;
    private gnosis.system.Cell cell23;
    private gnosis.system.Cell cell24;
    private gnosis.system.Cell cell25;
    private gnosis.system.Cell cell26;
    private gnosis.system.Cell cell27;
    private gnosis.system.Cell cell28;
    private gnosis.system.Cell cell29;
    private gnosis.system.Cell cell30;
    private gnosis.system.Cell cell31;
    private gnosis.system.Cell cell32;
    private gnosis.system.Cell cell33;
    private gnosis.system.Cell cell34;
    private gnosis.system.Cell cell35;
    private gnosis.system.Cell cell36;
    private gnosis.system.Cell cell37;
    private gnosis.system.Cell cell38;
    private gnosis.system.Cell cell39;
    private gnosis.system.Cell cell40;
    private gnosis.system.Cell cell41;
    private gnosis.system.Cell cell42;
    private gnosis.system.Cell cell43;
    private gnosis.system.Cell cell44;
    private gnosis.system.Cell cell45;
    private gnosis.system.Cell cell46;
    private gnosis.system.Cell cell47;
    private gnosis.system.Cell cell48;
    private gnosis.system.Cell cell49;
    private gnosis.system.Cell cell8;
    private gnosis.system.Cell cell9;
    private gnosis.system.Cell domingo;
    private gnosis.system.Cell jueves;
    private gnosis.system.Cell lunes;
    private gnosis.system.Cell martes;
    private gnosis.system.Cell miercoles;
    private gnosis.system.Cell sabado;
    private gnosis.system.Cell viernes;
    // End of variables declaration//GEN-END:variables
}
