/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gnosis.system;
//import Controller.CEstudents;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import Controller.CValidaciones;
import javax.swing.JOptionPane;
import Controller.CRecuperacionContra;

/**
 *
 * @author santi
 */
public class panPasswordRecover extends javax.swing.JPanel {

    /**
     * Creates new form panPasswordRecover
     */
    
    String codigoRandom;
    String correoRecu;
    String mensajeCortesia = "Tu codigo de recuperación de contraseña es: ";
    String asuntoDefaultRecover = "Recuperación de contraseña Gnosis System";
    
    public panPasswordRecover() {
        initComponents();
        
        //Componentes EMAIL
        btnConfirmar.setEnabled(false);
        btnGuardar.setEnabled(false);
        txtCodigo.setEnabled(false);
        txtNConfirmar.setEnabled(false);
        txtNueva.setEnabled(false);
        
        //Componentes PIN
        btnGuardarPIN.setEnabled(false);
        txtNuevaPIN.setEnabled(false);
        txtNConfirmarPIN.setEnabled(false);
        
        //Componentes ADMIN
        btnGuardarADMIN.setEnabled(false);
        txtCorreoRecuperar.setEnabled(false);
        txtNuevaADMIN.setEnabled(false);
        txtNConfirmarADMIN.setEnabled(false);
    }
    
    public boolean enviarCorreo(String mensaje, String asunto, String correo){
    boolean enviado = false;
        try{
            String de = "systemgnosis@gmail.com"; 
            String clave = "mvjmcsymrrypmnjc";
            String para = correo;
            String host = "smtp.gmail.com";

            Properties prop = System.getProperties();

            prop.put("mail.smtp.starttls.enable","true");
            prop.put("mail.smtp.host", host);
            prop.put("mail.smtp.user",de);
            prop.put("mail.smtp.password", clave);
            prop.put("mail.smtp.port",587);
            prop.put("mail.smtp.auth","true");

            Session sesion = Session.getDefaultInstance(prop,null);

            MimeMessage message = new MimeMessage(sesion);

            message.setFrom(new InternetAddress(de));

            message.setRecipient(Message.RecipientType.TO, new 
            InternetAddress(para));

            message.setSubject(asunto);
            message.setText(mensaje);

            Transport transport = sesion.getTransport("smtp");

            transport.connect(host,de,clave);

            transport.sendMessage(message, message.getAllRecipients());

            transport.close();

            enviado = true;

        }catch(Exception e){
            e.printStackTrace();
        }

    return enviado;
    
    
}
    public static String getRandomNumberString() {
    // It will generate 6 digit random Number.
    // from 0 to 999999
    Random rnd = new Random();
    int number = rnd.nextInt(999999);

    // this will convert any number sequence into 6 character.
    return String.format("%06d", number);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new customizeObjects.PanelRound();
        cardLayoutPan = new customizeObjects.PanelRound();
        metodos = new javax.swing.JPanel();
        btnPIN = new customizeObjects.ButtonRound();
        btnADMIN = new customizeObjects.ButtonRound();
        btnEMAIL = new customizeObjects.ButtonRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panPIN = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCorreoPIN = new javax.swing.JTextField();
        txtNuevaPIN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPIN = new javax.swing.JTextField();
        txtNConfirmarPIN = new javax.swing.JTextField();
        btnConfirmarPIN = new customizeObjects.ButtonRound();
        btnGuardarPIN = new customizeObjects.ButtonRound();
        buttonRound3 = new customizeObjects.ButtonRound();
        panADMIN = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCorreoADMIN = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNuevaADMIN = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtClaveADMIN = new javax.swing.JTextField();
        txtNConfirmarADMIN = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnConfirmarADMIN = new customizeObjects.ButtonRound();
        btnGuardarADMIN = new customizeObjects.ButtonRound();
        buttonRound6 = new customizeObjects.ButtonRound();
        txtCorreoRecuperar = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        panEMAIL = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtNueva = new javax.swing.JTextField();
        txtNConfirmar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        btnConfirmar = new customizeObjects.ButtonRound();
        btnGuardar = new customizeObjects.ButtonRound();
        buttonRound9 = new customizeObjects.ButtonRound();
        jLabel21 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnEnviar = new customizeObjects.ButtonRound();
        wContainer = new customizeObjects.PanelRound();
        loginWhitePan = new customizeObjects.PanelRound();
        lblInterfaz = new javax.swing.JLabel();
        topGap = new customizeObjects.PanelRound();
        rightWGap = new customizeObjects.PanelRound();
        leftWGap = new customizeObjects.PanelRound();

        LoginPanel.setBackground(new java.awt.Color(32, 32, 32));
        LoginPanel.setLayout(new javax.swing.BoxLayout(LoginPanel, javax.swing.BoxLayout.LINE_AXIS));

        cardLayoutPan.setBackground(new java.awt.Color(32, 32, 32));
        cardLayoutPan.setPreferredSize(new java.awt.Dimension(440, 550));
        cardLayoutPan.setLayout(new java.awt.CardLayout());

        metodos.setBackground(new java.awt.Color(32, 32, 32));
        metodos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PIN.png"))); // NOI18N
        btnPIN.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_ROJO);
        btnPIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPINMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPINMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPINMouseReleased(evt);
            }
        });
        btnPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPINActionPerformed(evt);
            }
        });
        metodos.add(btnPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 177, 128, 280));

        btnADMIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ADMIN.png"))); // NOI18N
        btnADMIN.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_ROJO);
        btnADMIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnADMINMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnADMINMouseReleased(evt);
            }
        });
        btnADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADMINActionPerformed(evt);
            }
        });
        metodos.add(btnADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 177, 132, 280));

        btnEMAIL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EMAIL.png"))); // NOI18N
        btnEMAIL.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_ROJO);
        btnEMAIL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEMAILMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEMAILMouseReleased(evt);
            }
        });
        btnEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEMAILActionPerformed(evt);
            }
        });
        metodos.add(btnEMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 177, 131, 280));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Escoge uno de los métodos para recuperar tu contraseña:");
        metodos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 119, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PIN de seguridad");
        metodos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 475, 128, 41));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Intervención de administrador");
        metodos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 475, 132, 41));
        jLabel2.setText("<html><center>" + "Intervención de administrador" + "</html></center>");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Correo electrónico");
        metodos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 475, 131, 41));

        cardLayoutPan.add(metodos, "card2");

        panPIN.setBackground(new java.awt.Color(32, 32, 32));
        panPIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Paso 1 - Ingresa tu correo y tu PIN de seguridad");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panPIN.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 48, 168, 43));
        jLabel5.setText("<html><center>" + "Paso 1 - Ingresa tu correo y tu PIN de seguridad" + "</center></html>");

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Paso 2 - Crea una nueva contraseña:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panPIN.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 48, 195, 43));
        jLabel6.setText("<html><center>" + "Paso 2 - Crea una nueva contraseña:" + "</center></html>");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel7.setText("Usuario o correo:");
        panPIN.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 141, -1, -1));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel8.setText("Contraseña nueva:");
        panPIN.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 141, -1, -1));

        txtCorreoPIN.setBackground(new java.awt.Color(77, 77, 77));
        txtCorreoPIN.setPreferredSize(new java.awt.Dimension(100, 30));
        panPIN.add(txtCorreoPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 183, 162, -1));

        txtNuevaPIN.setBackground(new java.awt.Color(77, 77, 77));
        txtNuevaPIN.setPreferredSize(new java.awt.Dimension(100, 30));
        panPIN.add(txtNuevaPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 183, 195, -1));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel9.setText("PIN:");
        panPIN.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 272, -1, -1));

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel10.setText("Confirmar contraseña:");
        panPIN.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 272, -1, -1));

        txtPIN.setBackground(new java.awt.Color(77, 77, 77));
        txtPIN.setPreferredSize(new java.awt.Dimension(100, 30));
        panPIN.add(txtPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 306, 162, -1));

        txtNConfirmarPIN.setBackground(new java.awt.Color(77, 77, 77));
        txtNConfirmarPIN.setPreferredSize(new java.awt.Dimension(100, 30));
        panPIN.add(txtNConfirmarPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 306, 195, -1));

        btnConfirmarPIN.setText("Confirmar");
        btnConfirmarPIN.setPreferredSize(new java.awt.Dimension(130, 40));
        btnConfirmarPIN.setRound(20);
        btnConfirmarPIN.setStyle(customizeObjects.ButtonRound.ButtonStyle.AMARILLO);
        btnConfirmarPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPINActionPerformed(evt);
            }
        });
        panPIN.add(btnConfirmarPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 391, -1, -1));

        btnGuardarPIN.setText("Guardar contraseña");
        btnGuardarPIN.setPreferredSize(new java.awt.Dimension(130, 40));
        btnGuardarPIN.setStyle(customizeObjects.ButtonRound.ButtonStyle.VERDE);
        btnGuardarPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPINActionPerformed(evt);
            }
        });
        panPIN.add(btnGuardarPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 391, -1, -1));

        buttonRound3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-right.png"))); // NOI18N
        buttonRound3.setText("Atras");
        buttonRound3.setIconTextGap(15);
        buttonRound3.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonRound3.setRound(20);
        buttonRound3.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        buttonRound3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound3ActionPerformed(evt);
            }
        });
        panPIN.add(buttonRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 511, 112, -1));

        cardLayoutPan.add(panPIN, "card3");

        panADMIN.setBackground(new java.awt.Color(32, 32, 32));
        panADMIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Paso 1 - Ingresa las credenciales de un administrador:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panADMIN.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 48, 168, 43));
        jLabel5.setText("<html><center>" + "Paso 1 - Ingresa tu correo y tu PIN de seguridad" + "</center></html>");

        jLabel12.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Paso 2 - Crea una nueva contraseña:");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panADMIN.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 48, 195, 43));
        jLabel6.setText("<html><center>" + "Paso 2 - Crea una nueva contraseña:" + "</center></html>");

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel13.setText("Usuario o correo: de admin:");
        panADMIN.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 141, -1, -1));

        txtCorreoADMIN.setBackground(new java.awt.Color(77, 77, 77));
        txtCorreoADMIN.setToolTipText("");
        txtCorreoADMIN.setPreferredSize(new java.awt.Dimension(100, 30));
        panADMIN.add(txtCorreoADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 183, 162, -1));

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel14.setText("Contraseña nueva:");
        panADMIN.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        txtNuevaADMIN.setBackground(new java.awt.Color(77, 77, 77));
        txtNuevaADMIN.setToolTipText("");
        txtNuevaADMIN.setPreferredSize(new java.awt.Dimension(100, 30));
        panADMIN.add(txtNuevaADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 195, -1));

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel15.setText("Contraseña:");
        panADMIN.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 272, -1, -1));

        txtClaveADMIN.setBackground(new java.awt.Color(77, 77, 77));
        txtClaveADMIN.setToolTipText("");
        txtClaveADMIN.setPreferredSize(new java.awt.Dimension(100, 30));
        panADMIN.add(txtClaveADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 306, 162, -1));

        txtNConfirmarADMIN.setBackground(new java.awt.Color(77, 77, 77));
        txtNConfirmarADMIN.setToolTipText("");
        txtNConfirmarADMIN.setPreferredSize(new java.awt.Dimension(100, 30));
        panADMIN.add(txtNConfirmarADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 195, -1));

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel16.setText("Confirmar contraseña:");
        panADMIN.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        btnConfirmarADMIN.setText("Confirmar");
        btnConfirmarADMIN.setPreferredSize(new java.awt.Dimension(130, 40));
        btnConfirmarADMIN.setRound(20);
        btnConfirmarADMIN.setStyle(customizeObjects.ButtonRound.ButtonStyle.AMARILLO);
        btnConfirmarADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarADMINActionPerformed(evt);
            }
        });
        panADMIN.add(btnConfirmarADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 391, -1, -1));

        btnGuardarADMIN.setText("Guardar contraseña");
        btnGuardarADMIN.setPreferredSize(new java.awt.Dimension(130, 40));
        btnGuardarADMIN.setStyle(customizeObjects.ButtonRound.ButtonStyle.VERDE);
        btnGuardarADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarADMINActionPerformed(evt);
            }
        });
        panADMIN.add(btnGuardarADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, -1, -1));

        buttonRound6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-right.png"))); // NOI18N
        buttonRound6.setText("Atras");
        buttonRound6.setIconTextGap(15);
        buttonRound6.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonRound6.setRound(20);
        buttonRound6.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        buttonRound6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound6ActionPerformed(evt);
            }
        });
        panADMIN.add(buttonRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 511, 112, -1));
        panADMIN.add(txtCorreoRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 195, 30));

        jLabel23.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel23.setText("Usuario o correo a recuperar:");
        panADMIN.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        cardLayoutPan.add(panADMIN, "card4");

        panEMAIL.setBackground(new java.awt.Color(32, 32, 32));
        panEMAIL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Paso 2 - Ingresa el codigo que recibiste en tu correo:");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panEMAIL.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 217, 168, 70));
        jLabel17.setText("<html><center>" + "Paso 2 - Ingresa el codigo enviado a tu correo" + "</center></html>");

        jLabel18.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Paso 3- Crea una nueva contraseña:");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panEMAIL.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 200, 60));
        jLabel18.setText("<html><center>" + "Paso 3 - Crea una nueva contraseña:" + "</center></html>");

        jLabel19.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("Codigo:");
        panEMAIL.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 293, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(77, 77, 77));
        txtCodigo.setPreferredSize(new java.awt.Dimension(100, 30));
        panEMAIL.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 315, 162, -1));

        jLabel20.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("Contraseña nueva:");
        panEMAIL.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 381, -1, -1));

        txtNueva.setBackground(new java.awt.Color(77, 77, 77));
        txtNueva.setPreferredSize(new java.awt.Dimension(100, 30));
        panEMAIL.add(txtNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 315, 200, -1));

        txtNConfirmar.setBackground(new java.awt.Color(77, 77, 77));
        txtNConfirmar.setPreferredSize(new java.awt.Dimension(100, 30));
        panEMAIL.add(txtNConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 407, 200, -1));

        jLabel22.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("Confirmar contraseña:");
        panEMAIL.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 293, -1, -1));

        btnConfirmar.setText("Confirmar");
        btnConfirmar.setPreferredSize(new java.awt.Dimension(130, 40));
        btnConfirmar.setRound(20);
        btnConfirmar.setStyle(customizeObjects.ButtonRound.ButtonStyle.AMARILLO);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        panEMAIL.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 402, -1, -1));

        btnGuardar.setText("Guardar contraseña");
        btnGuardar.setPreferredSize(new java.awt.Dimension(130, 40));
        btnGuardar.setStyle(customizeObjects.ButtonRound.ButtonStyle.VERDE);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panEMAIL.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 496, -1, -1));

        buttonRound9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-right.png"))); // NOI18N
        buttonRound9.setText("Atras");
        buttonRound9.setIconTextGap(15);
        buttonRound9.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonRound9.setRound(20);
        buttonRound9.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        buttonRound9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound9ActionPerformed(evt);
            }
        });
        panEMAIL.add(buttonRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 496, 112, -1));

        jLabel21.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("Paso 1 - Ingresa el correo electronico vinculado a la cuenta");
        jLabel21.setToolTipText("");
        panEMAIL.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 55, 350, -1));

        txtCorreo.setBackground(new java.awt.Color(77, 77, 77));
        txtCorreo.setPreferredSize(new java.awt.Dimension(100, 30));
        panEMAIL.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 84, 200, -1));

        btnEnviar.setText("Enviar codigo");
        btnEnviar.setPreferredSize(new java.awt.Dimension(130, 40));
        btnEnviar.setStyle(customizeObjects.ButtonRound.ButtonStyle.ROJO);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        panEMAIL.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 141, -1, -1));

        cardLayoutPan.add(panEMAIL, "card5");

        LoginPanel.add(cardLayoutPan);

        wContainer.setBackground(new java.awt.Color(255, 255, 255));
        wContainer.setPreferredSize(new java.awt.Dimension(437, 550));
        wContainer.setRoundBottomLeft(25);
        wContainer.setRoundBottomRight(25);
        wContainer.setRoundTopLeft(25);
        wContainer.setRoundTopRight(25);
        wContainer.setLayout(new java.awt.BorderLayout());

        loginWhitePan.setBackground(new java.awt.Color(255, 255, 255));
        loginWhitePan.setToolTipText("");
        loginWhitePan.setPreferredSize(new java.awt.Dimension(420, 430));

        lblInterfaz.setFont(new java.awt.Font("Poppins Black", 0, 24)); // NOI18N
        lblInterfaz.setForeground(new java.awt.Color(32, 32, 32));
        lblInterfaz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInterfaz.setText("Recuperación de Contraseña");

        javax.swing.GroupLayout loginWhitePanLayout = new javax.swing.GroupLayout(loginWhitePan);
        loginWhitePan.setLayout(loginWhitePanLayout);
        loginWhitePanLayout.setHorizontalGroup(
            loginWhitePanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginWhitePanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
        );
        loginWhitePanLayout.setVerticalGroup(
            loginWhitePanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginWhitePanLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(lblInterfaz)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        wContainer.add(loginWhitePan, java.awt.BorderLayout.CENTER);

        topGap.setBackground(new java.awt.Color(255, 255, 255));
        topGap.setPreferredSize(new java.awt.Dimension(437, 40));
        topGap.setRoundTopLeft(10);
        topGap.setRoundTopRight(10);
        topGap.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        wContainer.add(topGap, java.awt.BorderLayout.NORTH);

        rightWGap.setBackground(java.awt.Color.white);
        rightWGap.setPreferredSize(new java.awt.Dimension(10, 550));
        rightWGap.setRoundBottomRight(25);

        javax.swing.GroupLayout rightWGapLayout = new javax.swing.GroupLayout(rightWGap);
        rightWGap.setLayout(rightWGapLayout);
        rightWGapLayout.setHorizontalGroup(
            rightWGapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        rightWGapLayout.setVerticalGroup(
            rightWGapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        wContainer.add(rightWGap, java.awt.BorderLayout.EAST);

        leftWGap.setBackground(java.awt.Color.white);
        leftWGap.setPreferredSize(new java.awt.Dimension(10, 550));
        leftWGap.setRoundBottomLeft(25);

        javax.swing.GroupLayout leftWGapLayout = new javax.swing.GroupLayout(leftWGap);
        leftWGap.setLayout(leftWGapLayout);
        leftWGapLayout.setHorizontalGroup(
            leftWGapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        leftWGapLayout.setVerticalGroup(
            leftWGapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        wContainer.add(leftWGap, java.awt.BorderLayout.WEST);

        LoginPanel.add(wContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnADMINMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMINMousePressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnADMINMousePressed

    private void btnEMAILMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEMAILMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEMAILMousePressed

    private void btnPINMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPINMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPINMousePressed

    private void btnPINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPINMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPINMouseClicked

    private void btnPINMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPINMouseReleased
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btnPINMouseReleased

    private void btnADMINMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMINMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnADMINMouseReleased

    private void btnEMAILMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEMAILMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnEMAILMouseReleased

    private void btnPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPINActionPerformed
        // TODO add your handling code here:
        cardLayoutPan.removeAll();
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        cardLayoutPan.add(panPIN);
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();

        lblInterfaz.setText("<html><center>" + "Recuperación de contraseña: PIN de Seguridad" + "</center></html>");
    }//GEN-LAST:event_btnPINActionPerformed

    private void buttonRound3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound3ActionPerformed
        // TODO add your handling code here:
        cardLayoutPan.removeAll();
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        cardLayoutPan.add(metodos);
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        lblInterfaz.setText("<html><center>" + "Recuperación de contraseña" + "</center></html>");
    }//GEN-LAST:event_buttonRound3ActionPerformed

    private void buttonRound6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound6ActionPerformed
        // TODO add your handling code here:
        cardLayoutPan.removeAll();
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        cardLayoutPan.add(metodos);
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        lblInterfaz.setText("<html><center>" + "Recuperación de contraseña" + "</center></html>");
        
    }//GEN-LAST:event_buttonRound6ActionPerformed

    private void buttonRound9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound9ActionPerformed
        // TODO add your handling code here:
        cardLayoutPan.removeAll();
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        cardLayoutPan.add(metodos);
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        lblInterfaz.setText("<html><center>" + "Recuperación de contraseña" + "</center></html>");
    }//GEN-LAST:event_buttonRound9ActionPerformed

    private void btnADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADMINActionPerformed
        // TODO add your handling code here:
        cardLayoutPan.removeAll();
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        cardLayoutPan.add(panADMIN);
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();

        lblInterfaz.setText("<html><center>" + "Recuperación de contraseña: Intervención de administrador" + "</center></html>");
    }//GEN-LAST:event_btnADMINActionPerformed

    private void btnEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEMAILActionPerformed
        // TODO add your handling code here:
        cardLayoutPan.removeAll();
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        cardLayoutPan.add(panEMAIL);
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();

        lblInterfaz.setText("<html><center>" + "Recuperación de contraseña: Correo electrónico" + "</center></html>");
    }//GEN-LAST:event_btnEMAILActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        if (txtCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "vacio");
        }
        else   {
            codigoRandom = getRandomNumberString();
            correoRecu = txtCorreo.getText();
            JOptionPane.showMessageDialog(null, correoRecu);
            if (enviarCorreo(mensajeCortesia + codigoRandom, asuntoDefaultRecover, correoRecu)== true) {
                txtCorreo.setEditable(false);
                txtCodigo.setEnabled(true);
                btnConfirmar.setEnabled(true);             
            }
            
        }
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        if (txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "vacio");
        } else {
            String codigoIngresado = txtCodigo.getText();
            if (codigoIngresado.equals(codigoRandom)) {
                txtCodigo.setEditable(false);
                txtNConfirmar.setEnabled(true);
                txtNueva.setEnabled(true);
                btnGuardar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        if (txtNConfirmar.getText().isEmpty() && txtNueva.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"vacio como tu corazón");
        } else{
            if (txtNueva.getText().equals(txtNConfirmar.getText())) {
                CRecuperacionContra control = new CRecuperacionContra();
                control.clave = txtNueva.getText();
                control.correo = txtCorreo.getText();
                if (control.recu() == true) {
                    customization.notificacion("Contraseña reestablecida exitosamente", 1, "Recuperación contraseña");
//                    new frmLogin().setVisible(true);
                }
                else {
                    JOptionPane.showMessageDialog(null, "algo salio mal :P");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Las contraseñas no coninciden");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConfirmarPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPINActionPerformed
        // TODO add your handling code here:
        CRecuperacionContra control = new CRecuperacionContra();
        control.correo = txtCorreoPIN.getText();
        control.pin = Integer.parseInt(txtPIN.getText());
        if (control.recuPIN() == true) {
            customization.notificacion("Creedenciales confirmadas", 1, "PIN validado");
            txtNConfirmarPIN.setEnabled(true);
            txtNuevaPIN.setEnabled(true);
            btnGuardarPIN.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Las credenciales fracasaron");
        }
       
    }//GEN-LAST:event_btnConfirmarPINActionPerformed

    private void btnGuardarPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPINActionPerformed
        // TODO add your handling code here:
        if (txtNConfirmarPIN.getText().isEmpty() && txtNuevaPIN.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"vacio como tu corazón");
        } else{
            if (txtNConfirmarPIN.getText().equals(txtNuevaPIN.getText())) {
                CRecuperacionContra control = new CRecuperacionContra();
                control.clave = txtNuevaPIN.getText();
                control.correo = txtCorreoPIN.getText();
                if (control.recu() == true) {
                    customization.notificacion("Contraseña reestablecida exitosamente", 1, "Recuperación contraseña");
//                    new frmLogin().setVisible(true);
                }
                else {
                    JOptionPane.showMessageDialog(null, "algo salio mal :P");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Las contraseñas no coninciden");
            }
        }
    }//GEN-LAST:event_btnGuardarPINActionPerformed

    private void btnConfirmarADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarADMINActionPerformed
        // TODO add your handling code here:
        
        if (txtCorreoADMIN.getText().isEmpty() && txtClaveADMIN.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos vacios");
        } else{
            CRecuperacionContra control = new CRecuperacionContra();
            control.claveADMIN = txtClaveADMIN.getText();
            control.correoADMIN = txtCorreoADMIN.getText();
            if (control.recuADMIN() != null) {
                    customization.notificacion("Creedenciales confirmadas continua el proceso", 1, "Recuperación contraseña");
                        btnGuardarADMIN.setEnabled(true);
                        txtCorreoRecuperar.setEnabled(true);
                        txtNuevaADMIN.setEnabled(true);
                        txtNConfirmarADMIN.setEnabled(true);
                        
                        txtCorreoADMIN.setEditable(false);
                        txtClaveADMIN.setEditable(false);
//                    new frmLogin().setVisible(true);
            }
            else {
                JOptionPane.showMessageDialog(null, "algo salio mal :P");
            }
    }
    }//GEN-LAST:event_btnConfirmarADMINActionPerformed

    private void btnGuardarADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarADMINActionPerformed
        // TODO add your handling code here:
        
        if (txtNuevaADMIN.getText().isEmpty() && txtNConfirmarADMIN.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"vacio como tu corazón");
        } else{
            if (txtNuevaADMIN.getText().equals(txtNConfirmarADMIN.getText())) {
                CRecuperacionContra control = new CRecuperacionContra();
                control.clave = txtNuevaADMIN.getText();
                control.correo = txtCorreoRecuperar.getText();
                if (control.recu() == true) {
                    customization.notificacion("Contraseña reestablecida exitosamente", 1, "Recuperación contraseña");
//                    new frmLogin().setVisible(true);
                }
                else {
                    JOptionPane.showMessageDialog(null, "algo salio mal :P");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Las contraseñas no coninciden");
            }
        }
    }//GEN-LAST:event_btnGuardarADMINActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customizeObjects.PanelRound LoginPanel;
    private customizeObjects.ButtonRound btnADMIN;
    private customizeObjects.ButtonRound btnConfirmar;
    private customizeObjects.ButtonRound btnConfirmarADMIN;
    private customizeObjects.ButtonRound btnConfirmarPIN;
    private customizeObjects.ButtonRound btnEMAIL;
    private customizeObjects.ButtonRound btnEnviar;
    private customizeObjects.ButtonRound btnGuardar;
    private customizeObjects.ButtonRound btnGuardarADMIN;
    private customizeObjects.ButtonRound btnGuardarPIN;
    private customizeObjects.ButtonRound btnPIN;
    private customizeObjects.ButtonRound buttonRound3;
    private customizeObjects.ButtonRound buttonRound6;
    private customizeObjects.ButtonRound buttonRound9;
    private customizeObjects.PanelRound cardLayoutPan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblInterfaz;
    private customizeObjects.PanelRound leftWGap;
    private customizeObjects.PanelRound loginWhitePan;
    private javax.swing.JPanel metodos;
    private javax.swing.JPanel panADMIN;
    private javax.swing.JPanel panEMAIL;
    private javax.swing.JPanel panPIN;
    private customizeObjects.PanelRound rightWGap;
    private customizeObjects.PanelRound topGap;
    private javax.swing.JTextField txtClaveADMIN;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCorreoADMIN;
    private javax.swing.JTextField txtCorreoPIN;
    private javax.swing.JTextField txtCorreoRecuperar;
    private javax.swing.JTextField txtNConfirmar;
    private javax.swing.JTextField txtNConfirmarADMIN;
    private javax.swing.JTextField txtNConfirmarPIN;
    private javax.swing.JTextField txtNueva;
    private javax.swing.JTextField txtNuevaADMIN;
    private javax.swing.JTextField txtNuevaPIN;
    private javax.swing.JTextField txtPIN;
    private customizeObjects.PanelRound wContainer;
    // End of variables declaration//GEN-END:variables
}
