/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gnosis.system;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;

/**
 *
 * @author santi
 */
public class panPasswordRecover extends javax.swing.JPanel {

    /**
     * Creates new form panPasswordRecover
     */
    public panPasswordRecover() {
        initComponents();
        
    }
    
    public static void SendEmail() {    
      // Recipient's email ID needs to be mentioned.
      String to = "20190016@ricaldone.edu.sv";

      // Sender's email ID needs to be mentioned
      String from = "santiago.merino2004@gmail.com";

      // Assuming you are sending email from localhost
      String host = "localhost";

      // Get system properties
      Properties properties = System.getProperties();

      // Setup mail server
      properties.setProperty("mail.smtp.host", host);

      // Get the default Session object.
      Session session = Session.getDefaultInstance(properties);

      try {
         // Create a default MimeMessage object.
         MimeMessage message = new MimeMessage(session);

         // Set From: header field of the header.
         message.setFrom(new InternetAddress(from));

         // Set To: header field of the header.
         message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

         // Set Subject: header field
         message.setSubject("This is the Subject Line!");

         // Now set the actual message
         message.setText("This is actual message");

         // Send message
         Transport.send(message);
         System.out.println("Sent message successfully....");
      } catch (MessagingException mex) {
         mex.printStackTrace();
      }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new roundObjects.PanelRound();
        cardLayoutPan = new roundObjects.PanelRound();
        metodos = new javax.swing.JPanel();
        btnPIN = new roundObjects.ButtonRound();
        btnADMIN = new roundObjects.ButtonRound();
        btnEMAIL = new roundObjects.ButtonRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panPIN = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        buttonRound1 = new roundObjects.ButtonRound();
        buttonRound2 = new roundObjects.ButtonRound();
        buttonRound3 = new roundObjects.ButtonRound();
        panADMIN = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        buttonRound4 = new roundObjects.ButtonRound();
        buttonRound5 = new roundObjects.ButtonRound();
        buttonRound6 = new roundObjects.ButtonRound();
        panEMAIL = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        buttonRound7 = new roundObjects.ButtonRound();
        buttonRound8 = new roundObjects.ButtonRound();
        buttonRound9 = new roundObjects.ButtonRound();
        jLabel21 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        buttonRound10 = new roundObjects.ButtonRound();
        wContainer = new roundObjects.PanelRound();
        loginWhitePan = new roundObjects.PanelRound();
        lblInterfaz = new javax.swing.JLabel();
        topGap = new roundObjects.PanelRound();
        rightWGap = new roundObjects.PanelRound();
        leftWGap = new roundObjects.PanelRound();

        LoginPanel.setBackground(new java.awt.Color(32, 32, 32));
        LoginPanel.setLayout(new javax.swing.BoxLayout(LoginPanel, javax.swing.BoxLayout.LINE_AXIS));

        cardLayoutPan.setBackground(new java.awt.Color(32, 32, 32));
        cardLayoutPan.setPreferredSize(new java.awt.Dimension(440, 550));
        cardLayoutPan.setLayout(new java.awt.CardLayout());

        metodos.setBackground(new java.awt.Color(32, 32, 32));
        metodos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PIN.png"))); // NOI18N
        btnPIN.setStyle(roundObjects.ButtonRound.ButtonStyle.GRIS_ROJO);
        btnPIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPINMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPINMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPINMouseReleased(evt);
            }
        });
        btnPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPINActionPerformed(evt);
            }
        });
        metodos.add(btnPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 177, 128, 280));

        btnADMIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ADMIN.png"))); // NOI18N
        btnADMIN.setStyle(roundObjects.ButtonRound.ButtonStyle.GRIS_ROJO);
        btnADMIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnADMINMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnADMINMouseReleased(evt);
            }
        });
        btnADMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADMINActionPerformed(evt);
            }
        });
        metodos.add(btnADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 177, 132, 280));

        btnEMAIL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EMAIL.png"))); // NOI18N
        btnEMAIL.setStyle(roundObjects.ButtonRound.ButtonStyle.GRIS_ROJO);
        btnEMAIL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEMAILMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEMAILMouseReleased(evt);
            }
        });
        btnEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEMAILActionPerformed(evt);
            }
        });
        metodos.add(btnEMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 177, 131, 280));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Escoge uno de los métodos para recuperar tu contraseña:");
        metodos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 119, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PIN de seguridad");
        metodos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 475, 128, 41));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Intervención de administrador");
        metodos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 475, 132, 41));
        jLabel2.setText("<html><center>" + "Intervención de administrador" + "</html></center>");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Correo electrónico");
        metodos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 475, 131, 41));

        cardLayoutPan.add(metodos, "card2");

        panPIN.setBackground(new java.awt.Color(32, 32, 32));
        panPIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Paso 1 - Ingresa tu correo y tu PIN de seguridad");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panPIN.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 48, 168, 43));
        jLabel5.setText("<html><center>" + "Paso 1 - Ingresa tu correo y tu PIN de seguridad" + "</center></html>");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Paso 2 - Crea una nueva contraseña:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panPIN.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 48, 195, 43));
        jLabel6.setText("<html><center>" + "Paso 2 - Crea una nueva contraseña:" + "</center></html>");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel7.setText("Usuario o correo:");
        panPIN.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 141, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel8.setText("Contraseña nueva:");
        panPIN.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 141, -1, -1));

        jTextField1.setBackground(new java.awt.Color(77, 77, 77));
        jTextField1.setText("jTextField1");
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 30));
        panPIN.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 183, 162, -1));

        jTextField2.setBackground(new java.awt.Color(77, 77, 77));
        jTextField2.setText("jTextField2");
        jTextField2.setPreferredSize(new java.awt.Dimension(100, 30));
        panPIN.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 183, 195, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel9.setText("PIN:");
        panPIN.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 272, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel10.setText("Confirmar contraseña:");
        panPIN.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 272, -1, -1));

        jTextField3.setBackground(new java.awt.Color(77, 77, 77));
        jTextField3.setText("jTextField3");
        jTextField3.setPreferredSize(new java.awt.Dimension(100, 30));
        panPIN.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 306, 162, -1));

        jTextField4.setBackground(new java.awt.Color(77, 77, 77));
        jTextField4.setText("jTextField4");
        jTextField4.setPreferredSize(new java.awt.Dimension(100, 30));
        panPIN.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 306, 195, -1));

        buttonRound1.setText("Confirmar");
        buttonRound1.setPreferredSize(new java.awt.Dimension(130, 40));
        buttonRound1.setRound(20);
        buttonRound1.setStyle(roundObjects.ButtonRound.ButtonStyle.AMARILLO);
        panPIN.add(buttonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 391, -1, -1));

        buttonRound2.setText("Guardar contraseña");
        buttonRound2.setPreferredSize(new java.awt.Dimension(130, 40));
        buttonRound2.setStyle(roundObjects.ButtonRound.ButtonStyle.VERDE);
        panPIN.add(buttonRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 391, -1, -1));

        buttonRound3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-right.png"))); // NOI18N
        buttonRound3.setText("Atras");
        buttonRound3.setIconTextGap(15);
        buttonRound3.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonRound3.setRound(20);
        buttonRound3.setStyle(roundObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        buttonRound3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound3ActionPerformed(evt);
            }
        });
        panPIN.add(buttonRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 511, 112, -1));

        cardLayoutPan.add(panPIN, "card3");

        panADMIN.setBackground(new java.awt.Color(32, 32, 32));
        panADMIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Paso 1 - Ingresa las credenciales de un administrador:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panADMIN.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 48, 168, 43));
        jLabel5.setText("<html><center>" + "Paso 1 - Ingresa tu correo y tu PIN de seguridad" + "</center></html>");

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Paso 2 - Crea una nueva contraseña:");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panADMIN.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 48, 195, 43));
        jLabel6.setText("<html><center>" + "Paso 2 - Crea una nueva contraseña:" + "</center></html>");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel13.setText("Usuario o correo:");
        panADMIN.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 141, -1, -1));

        jTextField5.setBackground(new java.awt.Color(77, 77, 77));
        jTextField5.setText("jTextField1");
        jTextField5.setPreferredSize(new java.awt.Dimension(100, 30));
        panADMIN.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 183, 162, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel14.setText("Contraseña nueva:");
        panADMIN.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 141, -1, -1));

        jTextField6.setBackground(new java.awt.Color(77, 77, 77));
        jTextField6.setText("jTextField2");
        jTextField6.setPreferredSize(new java.awt.Dimension(100, 30));
        panADMIN.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 183, 195, -1));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel15.setText("Contraseña:");
        panADMIN.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 272, -1, -1));

        jTextField7.setBackground(new java.awt.Color(77, 77, 77));
        jTextField7.setText("jTextField3");
        jTextField7.setPreferredSize(new java.awt.Dimension(100, 30));
        panADMIN.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 306, 162, -1));

        jTextField8.setBackground(new java.awt.Color(77, 77, 77));
        jTextField8.setText("jTextField4");
        jTextField8.setPreferredSize(new java.awt.Dimension(100, 30));
        panADMIN.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 306, 195, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel16.setText("Confirmar contraseña:");
        panADMIN.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 272, -1, -1));

        buttonRound4.setText("Confirmar");
        buttonRound4.setPreferredSize(new java.awt.Dimension(130, 40));
        buttonRound4.setRound(20);
        buttonRound4.setStyle(roundObjects.ButtonRound.ButtonStyle.AMARILLO);
        panADMIN.add(buttonRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 391, -1, -1));

        buttonRound5.setText("Guardar contraseña");
        buttonRound5.setPreferredSize(new java.awt.Dimension(130, 40));
        buttonRound5.setStyle(roundObjects.ButtonRound.ButtonStyle.VERDE);
        panADMIN.add(buttonRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 391, -1, -1));

        buttonRound6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-right.png"))); // NOI18N
        buttonRound6.setText("Atras");
        buttonRound6.setIconTextGap(15);
        buttonRound6.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonRound6.setRound(20);
        buttonRound6.setStyle(roundObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        buttonRound6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound6ActionPerformed(evt);
            }
        });
        panADMIN.add(buttonRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 511, 112, -1));

        cardLayoutPan.add(panADMIN, "card4");

        panEMAIL.setBackground(new java.awt.Color(32, 32, 32));
        panEMAIL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Paso 2 - Ingresa las credenciales de un administrador:");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panEMAIL.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 227, 168, 43));
        jLabel17.setText("<html><center>" + "Paso 2 - Ingresa el codigo enviado a tu correo" + "</center></html>");

        jLabel18.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Paso 3- Crea una nueva contraseña:");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panEMAIL.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 227, 200, 43));
        jLabel18.setText("<html><center>" + "Paso 3 - Crea una nueva contraseña:" + "</center></html>");

        jLabel19.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("Usuario o correo:");
        panEMAIL.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 293, -1, -1));

        jTextField9.setBackground(new java.awt.Color(77, 77, 77));
        jTextField9.setPreferredSize(new java.awt.Dimension(100, 30));
        panEMAIL.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 315, 162, -1));

        jLabel20.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("Contraseña nueva:");
        panEMAIL.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 381, -1, -1));

        jTextField10.setBackground(new java.awt.Color(77, 77, 77));
        jTextField10.setPreferredSize(new java.awt.Dimension(100, 30));
        panEMAIL.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 315, 200, -1));

        jTextField12.setBackground(new java.awt.Color(77, 77, 77));
        jTextField12.setPreferredSize(new java.awt.Dimension(100, 30));
        panEMAIL.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 407, 200, -1));

        jLabel22.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("Confirmar contraseña:");
        panEMAIL.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 293, -1, -1));

        buttonRound7.setText("Confirmar");
        buttonRound7.setPreferredSize(new java.awt.Dimension(130, 40));
        buttonRound7.setRound(20);
        buttonRound7.setStyle(roundObjects.ButtonRound.ButtonStyle.AMARILLO);
        panEMAIL.add(buttonRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 402, -1, -1));

        buttonRound8.setText("Guardar contraseña");
        buttonRound8.setPreferredSize(new java.awt.Dimension(130, 40));
        buttonRound8.setStyle(roundObjects.ButtonRound.ButtonStyle.VERDE);
        panEMAIL.add(buttonRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 496, -1, -1));

        buttonRound9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-right.png"))); // NOI18N
        buttonRound9.setText("Atras");
        buttonRound9.setIconTextGap(15);
        buttonRound9.setPreferredSize(new java.awt.Dimension(100, 40));
        buttonRound9.setRound(20);
        buttonRound9.setStyle(roundObjects.ButtonRound.ButtonStyle.GRIS_OSCURO);
        buttonRound9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound9ActionPerformed(evt);
            }
        });
        panEMAIL.add(buttonRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 496, 112, -1));

        jLabel21.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("Paso 1 - Ingresa el correo electronico vinculado a la cuenta");
        jLabel21.setToolTipText("");
        panEMAIL.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 55, 350, -1));

        jTextField11.setBackground(new java.awt.Color(77, 77, 77));
        jTextField11.setPreferredSize(new java.awt.Dimension(100, 30));
        panEMAIL.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 84, 200, -1));

        buttonRound10.setText("Enviar codigo");
        buttonRound10.setPreferredSize(new java.awt.Dimension(130, 40));
        buttonRound10.setStyle(roundObjects.ButtonRound.ButtonStyle.ROJO);
        buttonRound10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound10ActionPerformed(evt);
            }
        });
        panEMAIL.add(buttonRound10, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 141, -1, -1));

        cardLayoutPan.add(panEMAIL, "card5");

        LoginPanel.add(cardLayoutPan);

        wContainer.setBackground(new java.awt.Color(255, 255, 255));
        wContainer.setPreferredSize(new java.awt.Dimension(437, 550));
        wContainer.setRoundBottomLeft(25);
        wContainer.setRoundBottomRight(25);
        wContainer.setRoundTopLeft(25);
        wContainer.setRoundTopRight(25);
        wContainer.setLayout(new java.awt.BorderLayout());

        loginWhitePan.setBackground(new java.awt.Color(255, 255, 255));
        loginWhitePan.setToolTipText("");
        loginWhitePan.setPreferredSize(new java.awt.Dimension(420, 430));

        lblInterfaz.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblInterfaz.setForeground(new java.awt.Color(32, 32, 32));
        lblInterfaz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInterfaz.setText("Recuperación de Contraseña");

        javax.swing.GroupLayout loginWhitePanLayout = new javax.swing.GroupLayout(loginWhitePan);
        loginWhitePan.setLayout(loginWhitePanLayout);
        loginWhitePanLayout.setHorizontalGroup(
            loginWhitePanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginWhitePanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
        );
        loginWhitePanLayout.setVerticalGroup(
            loginWhitePanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginWhitePanLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(lblInterfaz)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        wContainer.add(loginWhitePan, java.awt.BorderLayout.CENTER);

        topGap.setBackground(new java.awt.Color(255, 255, 255));
        topGap.setPreferredSize(new java.awt.Dimension(437, 40));
        topGap.setRoundTopLeft(10);
        topGap.setRoundTopRight(10);
        topGap.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        wContainer.add(topGap, java.awt.BorderLayout.NORTH);

        rightWGap.setBackground(java.awt.Color.white);
        rightWGap.setPreferredSize(new java.awt.Dimension(10, 550));
        rightWGap.setRoundBottomRight(25);

        javax.swing.GroupLayout rightWGapLayout = new javax.swing.GroupLayout(rightWGap);
        rightWGap.setLayout(rightWGapLayout);
        rightWGapLayout.setHorizontalGroup(
            rightWGapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        rightWGapLayout.setVerticalGroup(
            rightWGapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        wContainer.add(rightWGap, java.awt.BorderLayout.EAST);

        leftWGap.setBackground(java.awt.Color.white);
        leftWGap.setPreferredSize(new java.awt.Dimension(10, 550));
        leftWGap.setRoundBottomLeft(25);

        javax.swing.GroupLayout leftWGapLayout = new javax.swing.GroupLayout(leftWGap);
        leftWGap.setLayout(leftWGapLayout);
        leftWGapLayout.setHorizontalGroup(
            leftWGapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        leftWGapLayout.setVerticalGroup(
            leftWGapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        wContainer.add(leftWGap, java.awt.BorderLayout.WEST);

        LoginPanel.add(wContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnADMINMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMINMousePressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnADMINMousePressed

    private void btnEMAILMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEMAILMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEMAILMousePressed

    private void btnPINMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPINMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPINMousePressed

    private void btnPINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPINMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPINMouseClicked

    private void btnPINMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPINMouseReleased
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btnPINMouseReleased

    private void btnADMINMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMINMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnADMINMouseReleased

    private void btnEMAILMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEMAILMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnEMAILMouseReleased

    private void btnPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPINActionPerformed
        // TODO add your handling code here:
        cardLayoutPan.removeAll();
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        cardLayoutPan.add(panPIN);
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();

        lblInterfaz.setText("<html><center>" + "Recuperación de contraseña: PIN de Seguridad" + "</center></html>");
    }//GEN-LAST:event_btnPINActionPerformed

    private void buttonRound3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound3ActionPerformed
        // TODO add your handling code here:
        cardLayoutPan.removeAll();
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        cardLayoutPan.add(metodos);
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        lblInterfaz.setText("<html><center>" + "Recuperación de contraseña" + "</center></html>");
    }//GEN-LAST:event_buttonRound3ActionPerformed

    private void buttonRound6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound6ActionPerformed
        // TODO add your handling code here:
        cardLayoutPan.removeAll();
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        cardLayoutPan.add(metodos);
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        lblInterfaz.setText("<html><center>" + "Recuperación de contraseña" + "</center></html>");
        
    }//GEN-LAST:event_buttonRound6ActionPerformed

    private void buttonRound9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound9ActionPerformed
        // TODO add your handling code here:
        cardLayoutPan.removeAll();
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        cardLayoutPan.add(metodos);
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        lblInterfaz.setText("<html><center>" + "Recuperación de contraseña" + "</center></html>");
    }//GEN-LAST:event_buttonRound9ActionPerformed

    private void btnADMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADMINActionPerformed
        // TODO add your handling code here:
        cardLayoutPan.removeAll();
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        cardLayoutPan.add(panADMIN);
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();

        lblInterfaz.setText("<html><center>" + "Recuperación de contraseña: Intervención de administrador" + "</center></html>");
    }//GEN-LAST:event_btnADMINActionPerformed

    private void btnEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEMAILActionPerformed
        // TODO add your handling code here:
        cardLayoutPan.removeAll();
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();
        
        cardLayoutPan.add(panEMAIL);
        cardLayoutPan.repaint();
        cardLayoutPan.revalidate();

        lblInterfaz.setText("<html><center>" + "Recuperación de contraseña: Correo electrónico" + "</center></html>");
    }//GEN-LAST:event_btnEMAILActionPerformed

    private void buttonRound10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound10ActionPerformed
        // TODO add your handling code here:
        SendEmail();
    }//GEN-LAST:event_buttonRound10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private roundObjects.PanelRound LoginPanel;
    private roundObjects.ButtonRound btnADMIN;
    private roundObjects.ButtonRound btnEMAIL;
    private roundObjects.ButtonRound btnPIN;
    private roundObjects.ButtonRound buttonRound1;
    private roundObjects.ButtonRound buttonRound10;
    private roundObjects.ButtonRound buttonRound2;
    private roundObjects.ButtonRound buttonRound3;
    private roundObjects.ButtonRound buttonRound4;
    private roundObjects.ButtonRound buttonRound5;
    private roundObjects.ButtonRound buttonRound6;
    private roundObjects.ButtonRound buttonRound7;
    private roundObjects.ButtonRound buttonRound8;
    private roundObjects.ButtonRound buttonRound9;
    private roundObjects.PanelRound cardLayoutPan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblInterfaz;
    private roundObjects.PanelRound leftWGap;
    private roundObjects.PanelRound loginWhitePan;
    private javax.swing.JPanel metodos;
    private javax.swing.JPanel panADMIN;
    private javax.swing.JPanel panEMAIL;
    private javax.swing.JPanel panPIN;
    private roundObjects.PanelRound rightWGap;
    private roundObjects.PanelRound topGap;
    private roundObjects.PanelRound wContainer;
    // End of variables declaration//GEN-END:variables
}
