/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gnosis.system;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author santi
 */
public class panPortfolios extends javax.swing.JPanel {

    /**
     * Creates new form frmBlocNotas
     */
    public panPortfolios() {
        customization.mainUtilities();
        initComponents();
    }
    
    public boolean portfolioOpen(){
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPan = new javax.swing.JPanel();
        namePan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filtersPan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        mainPan = new javax.swing.JPanel();
        scrollPortfolios = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        matematicasPan = new roundObjects.PanelRound();
        panelRound1 = new roundObjects.PanelRound();
        panelRound2 = new roundObjects.PanelRound();
        buttonRound1 = new roundObjects.ButtonRound();
        inglesPan = new roundObjects.PanelRound();
        panelRound3 = new roundObjects.PanelRound();
        panelRound4 = new roundObjects.PanelRound();
        buttonRound2 = new roundObjects.ButtonRound();
        cienciasPan = new roundObjects.PanelRound();
        panelRound5 = new roundObjects.PanelRound();
        panelRound6 = new roundObjects.PanelRound();
        buttonRound3 = new roundObjects.ButtonRound();
        modulosPan = new roundObjects.PanelRound();
        panelRound7 = new roundObjects.PanelRound();
        panelRound8 = new roundObjects.PanelRound();
        buttonRound4 = new roundObjects.ButtonRound();
        lenguajePan = new roundObjects.PanelRound();
        panelRound9 = new roundObjects.PanelRound();
        panelRound10 = new roundObjects.PanelRound();
        buttonRound5 = new roundObjects.ButtonRound();
        socialesPan = new roundObjects.PanelRound();
        panelRound11 = new roundObjects.PanelRound();
        panelRound12 = new roundObjects.PanelRound();
        buttonRound6 = new roundObjects.ButtonRound();
        formaPan = new roundObjects.PanelRound();
        panelRound13 = new roundObjects.PanelRound();
        panelRound14 = new roundObjects.PanelRound();
        buttonRound7 = new roundObjects.ButtonRound();
        opvPan = new roundObjects.PanelRound();
        panelRound15 = new roundObjects.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelRound16 = new roundObjects.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        buttonRound8 = new roundObjects.ButtonRound();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        upperPan.setBackground(new java.awt.Color(255, 255, 255));
        upperPan.setPreferredSize(new java.awt.Dimension(766, 50));
        upperPan.setLayout(new javax.swing.BoxLayout(upperPan, javax.swing.BoxLayout.LINE_AXIS));

        namePan.setBackground(java.awt.Color.white);
        namePan.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 32, 32));
        jLabel1.setText("Portafolio");
        namePan.add(jLabel1, java.awt.BorderLayout.CENTER);

        upperPan.add(namePan);

        filtersPan.setBackground(new java.awt.Color(255, 255, 255));
        filtersPan.setForeground(new java.awt.Color(32, 32, 32));
        filtersPan.setPreferredSize(new java.awt.Dimension(555, 50));
        filtersPan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 32, 32));
        jLabel2.setText(" Categoria:");
        filtersPan.add(jLabel2);

        jComboBox1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jComboBox1.setForeground(java.awt.Color.white);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(100, 30));
        filtersPan.add(jComboBox1);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(32, 32, 32));
        jLabel3.setText("Ordenar:");
        filtersPan.add(jLabel3);

        jComboBox2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jComboBox2.setForeground(java.awt.Color.white);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox2.setPreferredSize(new java.awt.Dimension(100, 30));
        filtersPan.add(jComboBox2);

        upperPan.add(filtersPan);

        add(upperPan, java.awt.BorderLayout.NORTH);

        mainPan.setBackground(new java.awt.Color(255, 255, 255));
        mainPan.setPreferredSize(new java.awt.Dimension(800, 506));
        mainPan.setLayout(new java.awt.CardLayout());

        scrollPortfolios.setBackground(new java.awt.Color(217, 217, 217));
        scrollPortfolios.setBorder(null);
        scrollPortfolios.setForeground(new java.awt.Color(217, 217, 217));

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 900));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        matematicasPan.setBackground(new java.awt.Color(255, 153, 0));
        matematicasPan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        matematicasPan.setPreferredSize(new java.awt.Dimension(250, 350));
        matematicasPan.setRoundBottomLeft(20);
        matematicasPan.setRoundBottomRight(20);
        matematicasPan.setRoundTopLeft(20);
        matematicasPan.setRoundTopRight(20);

        panelRound1.setBackground(new java.awt.Color(255, 196, 32));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        panelRound2.setBackground(new java.awt.Color(255, 196, 32));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        buttonRound1.setText("Abrir");
        buttonRound1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        buttonRound1.setStyle(roundObjects.ButtonRound.ButtonStyle.NEGRO);
        buttonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout matematicasPanLayout = new javax.swing.GroupLayout(matematicasPan);
        matematicasPan.setLayout(matematicasPanLayout);
        matematicasPanLayout.setHorizontalGroup(
            matematicasPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, matematicasPanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(matematicasPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        matematicasPanLayout.setVerticalGroup(
            matematicasPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matematicasPanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel3.add(matematicasPan);

        inglesPan.setBackground(new java.awt.Color(255, 189, 62));
        inglesPan.setPreferredSize(new java.awt.Dimension(250, 350));
        inglesPan.setRoundBottomLeft(20);
        inglesPan.setRoundBottomRight(20);
        inglesPan.setRoundTopLeft(20);
        inglesPan.setRoundTopRight(20);

        panelRound3.setBackground(new java.awt.Color(255, 220, 100));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        panelRound4.setBackground(new java.awt.Color(255, 220, 100));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        buttonRound2.setText("Abrir");
        buttonRound2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        buttonRound2.setStyle(roundObjects.ButtonRound.ButtonStyle.NEGRO);

        javax.swing.GroupLayout inglesPanLayout = new javax.swing.GroupLayout(inglesPan);
        inglesPan.setLayout(inglesPanLayout);
        inglesPanLayout.setHorizontalGroup(
            inglesPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inglesPanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(inglesPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRound2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        inglesPanLayout.setVerticalGroup(
            inglesPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inglesPanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel3.add(inglesPan);

        cienciasPan.setBackground(new java.awt.Color(118, 221, 92));
        cienciasPan.setPreferredSize(new java.awt.Dimension(250, 350));
        cienciasPan.setRoundBottomLeft(20);
        cienciasPan.setRoundBottomRight(20);
        cienciasPan.setRoundTopLeft(20);
        cienciasPan.setRoundTopRight(20);

        panelRound5.setBackground(new java.awt.Color(140, 230, 130));
        panelRound5.setRoundBottomLeft(20);
        panelRound5.setRoundBottomRight(20);
        panelRound5.setRoundTopLeft(20);
        panelRound5.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        panelRound6.setBackground(new java.awt.Color(140, 230, 130));
        panelRound6.setRoundBottomLeft(20);
        panelRound6.setRoundBottomRight(20);
        panelRound6.setRoundTopLeft(20);
        panelRound6.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        buttonRound3.setText("Abrir");
        buttonRound3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        buttonRound3.setStyle(roundObjects.ButtonRound.ButtonStyle.NEGRO);

        javax.swing.GroupLayout cienciasPanLayout = new javax.swing.GroupLayout(cienciasPan);
        cienciasPan.setLayout(cienciasPanLayout);
        cienciasPanLayout.setHorizontalGroup(
            cienciasPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cienciasPanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cienciasPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRound3, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        cienciasPanLayout.setVerticalGroup(
            cienciasPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cienciasPanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel3.add(cienciasPan);

        modulosPan.setBackground(new java.awt.Color(32, 32, 32));
        modulosPan.setPreferredSize(new java.awt.Dimension(250, 350));
        modulosPan.setRoundBottomLeft(20);
        modulosPan.setRoundBottomRight(20);
        modulosPan.setRoundTopLeft(20);
        modulosPan.setRoundTopRight(20);

        panelRound7.setBackground(new java.awt.Color(80, 80, 80));
        panelRound7.setRoundBottomLeft(20);
        panelRound7.setRoundBottomRight(20);
        panelRound7.setRoundTopLeft(20);
        panelRound7.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        panelRound8.setBackground(new java.awt.Color(80, 80, 80));
        panelRound8.setRoundBottomLeft(20);
        panelRound8.setRoundBottomRight(20);
        panelRound8.setRoundTopLeft(20);
        panelRound8.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        buttonRound4.setText("Abrir");
        buttonRound4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        javax.swing.GroupLayout modulosPanLayout = new javax.swing.GroupLayout(modulosPan);
        modulosPan.setLayout(modulosPanLayout);
        modulosPanLayout.setHorizontalGroup(
            modulosPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modulosPanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(modulosPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRound4, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        modulosPanLayout.setVerticalGroup(
            modulosPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modulosPanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelRound7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(panelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRound4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel3.add(modulosPan);

        lenguajePan.setBackground(new java.awt.Color(227, 63, 63));
        lenguajePan.setPreferredSize(new java.awt.Dimension(250, 350));
        lenguajePan.setRoundBottomLeft(20);
        lenguajePan.setRoundBottomRight(20);
        lenguajePan.setRoundTopLeft(20);
        lenguajePan.setRoundTopRight(20);

        panelRound9.setBackground(new java.awt.Color(227, 80, 83));
        panelRound9.setRoundBottomLeft(20);
        panelRound9.setRoundBottomRight(20);
        panelRound9.setRoundTopLeft(20);
        panelRound9.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        panelRound10.setBackground(new java.awt.Color(227, 80, 83));
        panelRound10.setRoundBottomLeft(20);
        panelRound10.setRoundBottomRight(20);
        panelRound10.setRoundTopLeft(20);
        panelRound10.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound10Layout = new javax.swing.GroupLayout(panelRound10);
        panelRound10.setLayout(panelRound10Layout);
        panelRound10Layout.setHorizontalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound10Layout.setVerticalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        buttonRound5.setText("Abrir");
        buttonRound5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        javax.swing.GroupLayout lenguajePanLayout = new javax.swing.GroupLayout(lenguajePan);
        lenguajePan.setLayout(lenguajePanLayout);
        lenguajePanLayout.setHorizontalGroup(
            lenguajePanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lenguajePanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lenguajePanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRound5, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        lenguajePanLayout.setVerticalGroup(
            lenguajePanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lenguajePanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelRound9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(panelRound10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRound5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel3.add(lenguajePan);

        socialesPan.setBackground(new java.awt.Color(98, 148, 244));
        socialesPan.setPreferredSize(new java.awt.Dimension(250, 350));
        socialesPan.setRoundBottomLeft(20);
        socialesPan.setRoundBottomRight(20);
        socialesPan.setRoundTopLeft(20);
        socialesPan.setRoundTopRight(20);

        panelRound11.setBackground(new java.awt.Color(120, 160, 244));
        panelRound11.setRoundBottomLeft(20);
        panelRound11.setRoundBottomRight(20);
        panelRound11.setRoundTopLeft(20);
        panelRound11.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound11Layout = new javax.swing.GroupLayout(panelRound11);
        panelRound11.setLayout(panelRound11Layout);
        panelRound11Layout.setHorizontalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound11Layout.setVerticalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        panelRound12.setBackground(new java.awt.Color(120, 160, 244));
        panelRound12.setRoundBottomLeft(20);
        panelRound12.setRoundBottomRight(20);
        panelRound12.setRoundTopLeft(20);
        panelRound12.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound12Layout = new javax.swing.GroupLayout(panelRound12);
        panelRound12.setLayout(panelRound12Layout);
        panelRound12Layout.setHorizontalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound12Layout.setVerticalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        buttonRound6.setBackground(new java.awt.Color(32, 32, 32));
        buttonRound6.setText("Abrir");
        buttonRound6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        buttonRound6.setStyle(roundObjects.ButtonRound.ButtonStyle.NEGRO);

        javax.swing.GroupLayout socialesPanLayout = new javax.swing.GroupLayout(socialesPan);
        socialesPan.setLayout(socialesPanLayout);
        socialesPanLayout.setHorizontalGroup(
            socialesPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, socialesPanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(socialesPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRound6, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        socialesPanLayout.setVerticalGroup(
            socialesPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(socialesPanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelRound11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(panelRound12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRound6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel3.add(socialesPan);

        formaPan.setBackground(new java.awt.Color(95, 125, 85));
        formaPan.setPreferredSize(new java.awt.Dimension(250, 350));
        formaPan.setRoundBottomLeft(20);
        formaPan.setRoundBottomRight(20);
        formaPan.setRoundTopLeft(20);
        formaPan.setRoundTopRight(20);

        panelRound13.setBackground(new java.awt.Color(110, 125, 100));
        panelRound13.setRoundBottomLeft(20);
        panelRound13.setRoundBottomRight(20);
        panelRound13.setRoundTopLeft(20);
        panelRound13.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound13Layout = new javax.swing.GroupLayout(panelRound13);
        panelRound13.setLayout(panelRound13Layout);
        panelRound13Layout.setHorizontalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound13Layout.setVerticalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        panelRound14.setBackground(new java.awt.Color(110, 125, 100));
        panelRound14.setRoundBottomLeft(20);
        panelRound14.setRoundBottomRight(20);
        panelRound14.setRoundTopLeft(20);
        panelRound14.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound14Layout = new javax.swing.GroupLayout(panelRound14);
        panelRound14.setLayout(panelRound14Layout);
        panelRound14Layout.setHorizontalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRound14Layout.setVerticalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        buttonRound7.setText("Abrir");
        buttonRound7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        javax.swing.GroupLayout formaPanLayout = new javax.swing.GroupLayout(formaPan);
        formaPan.setLayout(formaPanLayout);
        formaPanLayout.setHorizontalGroup(
            formaPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formaPanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formaPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRound7, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        formaPanLayout.setVerticalGroup(
            formaPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formaPanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelRound13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(panelRound14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRound7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel3.add(formaPan);

        opvPan.setBackground(new java.awt.Color(60, 80, 120));
        opvPan.setPreferredSize(new java.awt.Dimension(250, 350));
        opvPan.setRoundBottomLeft(20);
        opvPan.setRoundBottomRight(20);
        opvPan.setRoundTopLeft(20);
        opvPan.setRoundTopRight(20);

        panelRound15.setBackground(new java.awt.Color(60, 100, 130));
        panelRound15.setRoundBottomLeft(20);
        panelRound15.setRoundBottomRight(20);
        panelRound15.setRoundTopLeft(20);
        panelRound15.setRoundTopRight(20);
        panelRound15.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Grado");
        panelRound15.add(jLabel4, java.awt.BorderLayout.CENTER);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Materia");
        jLabel5.setPreferredSize(new java.awt.Dimension(70, 70));
        panelRound15.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Docente");
        jLabel6.setPreferredSize(new java.awt.Dimension(41, 60));
        panelRound15.add(jLabel6, java.awt.BorderLayout.PAGE_END);

        panelRound16.setBackground(new java.awt.Color(60, 100, 130));
        panelRound16.setRoundBottomLeft(20);
        panelRound16.setRoundBottomRight(20);
        panelRound16.setRoundTopLeft(20);
        panelRound16.setRoundTopRight(20);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("# Páginas");

        javax.swing.GroupLayout panelRound16Layout = new javax.swing.GroupLayout(panelRound16);
        panelRound16.setLayout(panelRound16Layout);
        panelRound16Layout.setHorizontalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound16Layout.setVerticalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        buttonRound8.setText("Abrir");
        buttonRound8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        javax.swing.GroupLayout opvPanLayout = new javax.swing.GroupLayout(opvPan);
        opvPan.setLayout(opvPanLayout);
        opvPanLayout.setHorizontalGroup(
            opvPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opvPanLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(opvPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRound15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRound8, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        opvPanLayout.setVerticalGroup(
            opvPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opvPanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelRound15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(panelRound16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRound8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel3.add(opvPan);

        scrollPortfolios.setViewportView(jPanel3);

        mainPan.add(scrollPortfolios, "card2");

        add(mainPan, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound1ActionPerformed
        // TODO add your handling code here:
//        upperPan.setPreferredSize(new Dimension(100,0));
//        mainPan.removeAll();
//        mainPan.repaint();
//        mainPan.revalidate();
//
//        mainPan.add(new panBlocMateria());
//        mainPan.repaint();
//        mainPan.revalidate(); 
//        mainPan.setBackground(new Color(32,32,32));
        frmDashboard dash = new frmDashboard();
        dash.setVisible(true);
        dash.AbrirBloc();
        
        JFrame dashboardopen = (JFrame) SwingUtilities.getWindowAncestor(this);
        dashboardopen.dispose();
    }//GEN-LAST:event_buttonRound1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private roundObjects.ButtonRound buttonRound1;
    private roundObjects.ButtonRound buttonRound2;
    private roundObjects.ButtonRound buttonRound3;
    private roundObjects.ButtonRound buttonRound4;
    private roundObjects.ButtonRound buttonRound5;
    private roundObjects.ButtonRound buttonRound6;
    private roundObjects.ButtonRound buttonRound7;
    private roundObjects.ButtonRound buttonRound8;
    private roundObjects.PanelRound cienciasPan;
    private javax.swing.JPanel filtersPan;
    private roundObjects.PanelRound formaPan;
    private roundObjects.PanelRound inglesPan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private roundObjects.PanelRound lenguajePan;
    private javax.swing.JPanel mainPan;
    private roundObjects.PanelRound matematicasPan;
    private roundObjects.PanelRound modulosPan;
    private javax.swing.JPanel namePan;
    private roundObjects.PanelRound opvPan;
    private roundObjects.PanelRound panelRound1;
    private roundObjects.PanelRound panelRound10;
    private roundObjects.PanelRound panelRound11;
    private roundObjects.PanelRound panelRound12;
    private roundObjects.PanelRound panelRound13;
    private roundObjects.PanelRound panelRound14;
    private roundObjects.PanelRound panelRound15;
    private roundObjects.PanelRound panelRound16;
    private roundObjects.PanelRound panelRound2;
    private roundObjects.PanelRound panelRound3;
    private roundObjects.PanelRound panelRound4;
    private roundObjects.PanelRound panelRound5;
    private roundObjects.PanelRound panelRound6;
    private roundObjects.PanelRound panelRound7;
    private roundObjects.PanelRound panelRound8;
    private roundObjects.PanelRound panelRound9;
    private javax.swing.JScrollPane scrollPortfolios;
    private roundObjects.PanelRound socialesPan;
    private javax.swing.JPanel upperPan;
    // End of variables declaration//GEN-END:variables
}
