/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gnosis.system;

import Controller.CTasks;
import java.awt.Frame;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class panTasks extends javax.swing.JPanel {

    /**
     * Creates new form frmprueba
     */
    customization custo = new customization();
    CTasks controller = new CTasks();
    int nivelusuario;
    int iddocente;
    
    public panTasks(int nivel) {
        initComponents();
        nivelusuario = nivel;
        iddocente = 0;
        btnAgregarTarea.setVisible(false);
        CargarTareasAlumnos();
    }
    
    public panTasks(int nivel, int iddocente){
        initComponents();
        nivelusuario = nivel;
        if (nivelusuario == 3) {
            this.iddocente = 0;
        } else {
            this.iddocente = iddocente;
        }
        CargarTareasDocente(iddocente);
    }
    
    
    final void CargarTareasAlumnos(){
        controller = new CTasks();
        ResultSet datos = controller.CargarTareasPreview();
        try {
            while (datos.next()) {  
                //Forma de corroborar si es una materia o un modulo :3
                int fila = datos.getRow();
                String materiamodulo;
                String cadena = datos.getString(4);     
                String[] palabras = cadena.split(" ", 2);
                if (palabras[0].equals("Ninguno")) {
                    materiamodulo = palabras[1];
                } else {
                    materiamodulo = cadena.substring(0, cadena.lastIndexOf(" "));
                }               
                custo.CrearTarea(datos.getString(1), materiamodulo, datos.getString(5), datos.getString(2), datos.getString(3), datos.getString(6), mainPan, materiamodulo, datos.getInt(10), nivelusuario);
//                System.out.println(datos.absolute(fila));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudieron cargar las tareas " + e.toString());
        }
        
    }
    
        final void CargarTareasDocente(int iddocente){
        controller = new CTasks();
        ResultSet datos = controller.CargarTareasPreviewDocente(iddocente);
        try {
            while (datos.next()) {  
                //Forma de corroborar si es una materia o un modulo :3
                int fila = datos.getRow();
                String materiamodulo;
                String cadena = datos.getString(4);     
                String[] palabras = cadena.split(" ", 2);
                if (palabras[0].equals("Ninguno")) {
                    materiamodulo = palabras[1];
                } else {
                    materiamodulo = cadena.substring(0, cadena.lastIndexOf(" "));
                }               
                custo.CrearTarea(datos.getString(1), materiamodulo, datos.getString(5), datos.getString(2), datos.getString(3), datos.getString(6), mainPan, materiamodulo, datos.getInt(10), nivelusuario);
//                System.out.println(datos.absolute(fila));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudieron cargar las tareas " + e.toString());
        }
        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainPan = new javax.swing.JPanel();
        upperPan = new javax.swing.JPanel();
        namePan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filtersPan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        btnAgregarTarea = new customizeObjects.ButtonRound();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);

        mainPan.setBackground(new java.awt.Color(255, 255, 255));
        mainPan.setMaximumSize(new java.awt.Dimension(1500, 10));
        mainPan.setMinimumSize(new java.awt.Dimension(1000, 10));
        mainPan.setLayout(new java.awt.GridLayout(20, 0));
        jScrollPane1.setViewportView(mainPan);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        upperPan.setBackground(java.awt.Color.white);
        upperPan.setPreferredSize(new java.awt.Dimension(1000, 50));
        upperPan.setLayout(new java.awt.BorderLayout());

        namePan.setBackground(new java.awt.Color(255, 255, 255));
        namePan.setPreferredSize(new java.awt.Dimension(200, 50));
        namePan.setLayout(new javax.swing.BoxLayout(namePan, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Tareas");
        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 32, 32));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 50));
        namePan.add(jLabel1);

        upperPan.add(namePan, java.awt.BorderLayout.WEST);

        filtersPan.setBackground(java.awt.Color.white);
        filtersPan.setPreferredSize(new java.awt.Dimension(500, 50));
        filtersPan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 10));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 32, 32));
        jLabel2.setText("Ordenar:");
        filtersPan.add(jLabel2);

        cmbTipo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calificado", "Completado" }));
        cmbTipo.setPreferredSize(new java.awt.Dimension(100, 30));
        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });
        filtersPan.add(cmbTipo);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(32, 32, 32));
        jLabel3.setText("Filtrar:");
        filtersPan.add(jLabel3);

        cmbEstado.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proyecto Formativo", "Recuperacion", "Cotidianas" }));
        cmbEstado.setPreferredSize(new java.awt.Dimension(100, 30));
        cmbEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEstadoItemStateChanged(evt);
            }
        });
        filtersPan.add(cmbEstado);

        btnAgregarTarea.setText("Gestionar Tareas");
        btnAgregarTarea.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnAgregarTarea.setRound(15);
        btnAgregarTarea.setStyle(customizeObjects.ButtonRound.ButtonStyle.GRIS_ROJO);
        btnAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTareaActionPerformed(evt);
            }
        });
        filtersPan.add(btnAgregarTarea);

        upperPan.add(filtersPan, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(32, 32, 32));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Estado:");
        jLabel4.setAlignmentY(0.0F);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, java.awt.BorderLayout.CENTER);

        upperPan.add(jPanel1, java.awt.BorderLayout.EAST);

        add(upperPan, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTareaActionPerformed
        // TODO add your handling code here:
        frmTasks task = new frmTasks();
        task.setVisible(true);
    }//GEN-LAST:event_btnAgregarTareaActionPerformed
    
    final void CargarTareasTipo(){
        String tipo = (String) cmbTipo.getSelectedItem();
        ResultSet datos = controller.CargarTareasFiltro(tipo, iddocente);
        mainPan.removeAll();
        mainPan.revalidate();
        mainPan.repaint();
        controller = new CTasks();
        try {
            while (datos.next()) {
                //Forma de corroborar si es una materia o un modulo :3
                int fila = datos.getRow();
                String materiamodulo;
                String cadena = datos.getString(4);
                String[] palabras = cadena.split(" ", 2);
                if (palabras[0].equals("Ninguno")) {
                    materiamodulo = palabras[1];
                } else {
                    materiamodulo = cadena.substring(0, cadena.lastIndexOf(" "));
                }
                custo.CrearTarea(datos.getString(1), materiamodulo, datos.getString(5), datos.getString(2), datos.getString(3), datos.getString(6), mainPan, materiamodulo, datos.getInt(10), nivelusuario);
//                System.out.println(datos.absolute(fila));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudieron cargar las tareas " + e.toString());
        }
    }
    
    final void CargarTareasEstado(){
        mainPan.removeAll();
        mainPan.revalidate();
        mainPan.repaint();
        CTasks controller = new CTasks();
        String tipo = (String) cmbEstado.getSelectedItem();
        ResultSet datos = controller.CargarTareasFiltroEstado(tipo, iddocente);
        try {
            while (datos.next()) {  
                //Forma de corroborar si es una materia o un modulo :3
                int fila = datos.getRow();
                String materiamodulo;
                String cadena = datos.getString(4);     
                String[] palabras = cadena.split(" ", 2);
                if (palabras[0].equals("Ninguno")) {
                    materiamodulo = palabras[1];
                } else {
                    materiamodulo = cadena.substring(0, cadena.lastIndexOf(" "));
                }               
                custo.CrearTarea(datos.getString(1), materiamodulo, datos.getString(5), datos.getString(2), datos.getString(3), datos.getString(6), mainPan, materiamodulo, datos.getInt(10), nivelusuario);
//                System.out.println(datos.absolute(fila));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudieron cargar las tareas " + e.toString());
        }
        
    }
    
    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged
        // TODO add your handling code here:
        CargarTareasTipo();
    }//GEN-LAST:event_cmbTipoItemStateChanged

    private void cmbEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEstadoItemStateChanged
        // TODO add your handling code here:
        CargarTareasEstado();
    }//GEN-LAST:event_cmbEstadoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customizeObjects.ButtonRound btnAgregarTarea;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JPanel filtersPan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPan;
    private javax.swing.JPanel namePan;
    private javax.swing.JPanel upperPan;
    // End of variables declaration//GEN-END:variables
}
