/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package customizeObjects;

import Controller.CEvento;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import customizeObjects.Cell;
import java.awt.BorderLayout;
import javax.swing.JLabel;

/**
 *
 * @author santi
 */
public class CalendarCustom extends javax.swing.JPanel {

    /**
     * Creates new form CalendarCustom
     */
    private int month;
    private int year;
    public String fechaseleccionada;
    public String valor;
    
    public int daySelec;

    public String getFechaseleccionada() {
        return fechaseleccionada;
    }

    public void setFechaseleccionada(String fechaseleccionada) {
        this.fechaseleccionada = fechaseleccionada;
    }

    public CalendarCustom(String fechaseleccionada) {
        this.fechaseleccionada = fechaseleccionada;
    }
    
    
    public CalendarCustom() {
        initComponents();
        thisMonth();
        slide.show(new PanelDate( 9, 2022), PanelSlide.AnimateType.TO_RIGHT);
        showMonthYear();
        Dimension dim = getSize();
        setSize(dim);
        
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        System.err.println(e);
                    }
                    Date date = new Date();
                    SimpleDateFormat tf = new SimpleDateFormat("h:mm:ss aa");
                    SimpleDateFormat df = new SimpleDateFormat("EEEE, dd/MMMM/yyyy");
                    String time = tf.format(date);
                    lblTime.setText(time.split(" ")[0]);
                    lblType.setText(time.split(" ")[1]);
                    lblDate.setText(df.format(date));
//                    SetearTexto();
                }                  
            }
        }).start();
    }
   
    //
    public void SetearTexto(JLabel fecha){
        new Thread(new Runnable() {
            @Override
            public void run(){
                CEvento eventoscontroller = new CEvento();
                eventoscontroller.EventoNuevoResultSet();
                
            }
        }).start(); 
        
    }
////
    
//    public void CambiarTexto(){
//        PanelDate panelhijo = new PanelDate();
//        this.fechaseleccionada = panelhijo.fechaseleccionada;
//        lblFechaSeleccionada.setText(fechaseleccionada);
//        JOptionPane.showMessageDialog(null, "Si llega y esto es una mierda: " + fechaseleccionada);
//    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelPrincipal = new customizeObjects.PanelRound();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnNext = new customizeObjects.ButtonRound();
        btnBack = new customizeObjects.ButtonRound();
        lblMesAño = new javax.swing.JLabel();
        slide = new customizeObjects.PanelSlide();

        setBackground(java.awt.Color.white);
        setLayout(new java.awt.BorderLayout());

        panelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        panelSuperior.setForeground(new java.awt.Color(255, 255, 255));
        panelSuperior.setPreferredSize(new java.awt.Dimension(100, 60));
        panelSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 32, 32));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calendario");
        panelSuperior.add(jLabel1);

        lblTime.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(32, 32, 32));
        lblTime.setText("TIME");
        panelSuperior.add(lblTime);

        lblType.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblType.setForeground(new java.awt.Color(32, 32, 32));
        lblType.setText("type");
        panelSuperior.add(lblType);

        lblDate.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(32, 32, 32));
        lblDate.setText("DATE");
        panelSuperior.add(lblDate);

        add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(300, 448));
        jPanel3.setLayout(new java.awt.CardLayout());
        add(jPanel3, java.awt.BorderLayout.EAST);

        panelPrincipal.setBackground(new java.awt.Color(32, 32, 32));
        panelPrincipal.setRoundBottomLeft(20);
        panelPrincipal.setRoundBottomRight(20);
        panelPrincipal.setRoundTopLeft(20);
        panelPrincipal.setRoundTopRight(20);
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLayeredPane1.setBackground(new java.awt.Color(32, 32, 32));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new java.awt.BorderLayout());

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-right-x30.png"))); // NOI18N
        btnNext.setPreferredSize(new java.awt.Dimension(35, 35));
        btnNext.setRound(15);
        btnNext.setStyle(customizeObjects.ButtonRound.ButtonStyle.NEGRO);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnNext, java.awt.BorderLayout.EAST);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-let-x30.png"))); // NOI18N
        btnBack.setPreferredSize(new java.awt.Dimension(35, 35));
        btnBack.setRound(15);
        btnBack.setStyle(customizeObjects.ButtonRound.ButtonStyle.NEGRO);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnBack, java.awt.BorderLayout.WEST);

        lblMesAño.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lblMesAño.setForeground(new java.awt.Color(255, 255, 255));
        lblMesAño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMesAño.setText("Mes - Año");
        lblMesAño.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblMesAño.setPreferredSize(new java.awt.Dimension(129, 50));
        jLayeredPane1.add(lblMesAño, java.awt.BorderLayout.CENTER);

        jPanel1.add(jLayeredPane1, java.awt.BorderLayout.NORTH);

        slide.setBackground(new java.awt.Color(32, 32, 32));

        javax.swing.GroupLayout slideLayout = new javax.swing.GroupLayout(slide);
        slide.setLayout(slideLayout);
        slideLayout.setHorizontalGroup(
            slideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        slideLayout.setVerticalGroup(
            slideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jPanel1.add(slide, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(panelPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if (month == 12) {
            month = 1;
            year++;
        } else{
            month++;
        }
        slide.show(new PanelDate(month, year), PanelSlide.AnimateType.TO_LEFT);
        showMonthYear();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if (month == 1) {
            month = 12;
            year--;
        } else{
            month--;
        }
        slide.show(new PanelDate(month, year), PanelSlide.AnimateType.TO_RIGHT);
        showMonthYear();
    }//GEN-LAST:event_btnBackActionPerformed

    private void thisMonth(){
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());
        month = calendar.get(Calendar.MONTH) +1;
        year = calendar.get(Calendar.YEAR);
    }
    
    private void showMonthYear(){
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.MONTH, month - 1);
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.DATE, 1);
        SimpleDateFormat df = new SimpleDateFormat("MMMM-yyyy");
        lblMesAño.setText(df.format(calendar.getTime()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customizeObjects.ButtonRound btnBack;
    private customizeObjects.ButtonRound btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMesAño;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblType;
    private customizeObjects.PanelRound panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private customizeObjects.PanelSlide slide;
    // End of variables declaration//GEN-END:variables
}
