/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package customizeObjects;

import customizeObjects.PanelSlide;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author santi
 */
public class CalendarCustom extends javax.swing.JPanel {

    /**
     * Creates new form CalendarCustom
     */
    private int month;
    private int year;
    
    public CalendarCustom() {
        initComponents();
        thisMonth();
        slide.show(new PanelDate( 9, 2022), PanelSlide.AnimateType.TO_RIGHT);
        showMonthYear();
//        
//        new Thread(new Runnable() {
//            @Override
//            public void run() {
//                while (true) {
//                    try {
//                        Thread.sleep(1000);
//                    } catch (InterruptedException e) {
//                        System.err.println(e);
//                    }
//                    Date date = new Date();
//                    SimpleDateFormat tf = new SimpleDateFormat("h:mm:ss aa");
//                    SimpleDateFormat df = new SimpleDateFormat("EEEE, dd/MM-yyyy");
//                    String time = tf.format(date);
////                    lblTime.setText(time.split(" ")[0]);
////                    lblType.setText(time.split(" ")[1]);
////                    lblDate.setText(df.format(date));
//                }
//            }
//        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnNext = new customizeObjects.ButtonRound();
        btnBack = new customizeObjects.ButtonRound();
        lblMesAño = new javax.swing.JLabel();
        slide = new customizeObjects.PanelSlide();

        setBackground(new java.awt.Color(32, 32, 32));
        setLayout(new java.awt.BorderLayout());

        jLayeredPane1.setBackground(new java.awt.Color(32, 32, 32));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new java.awt.BorderLayout());

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-right-x30.png"))); // NOI18N
        btnNext.setPreferredSize(new java.awt.Dimension(35, 35));
        btnNext.setRound(0);
        btnNext.setStyle(customizeObjects.ButtonRound.ButtonStyle.NEGRO);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnNext, java.awt.BorderLayout.EAST);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-let-x30.png"))); // NOI18N
        btnBack.setPreferredSize(new java.awt.Dimension(35, 35));
        btnBack.setRound(0);
        btnBack.setStyle(customizeObjects.ButtonRound.ButtonStyle.NEGRO);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btnBack, java.awt.BorderLayout.WEST);

        lblMesAño.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        lblMesAño.setForeground(new java.awt.Color(255, 255, 255));
        lblMesAño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMesAño.setText("Mes - Año");
        lblMesAño.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblMesAño.setPreferredSize(new java.awt.Dimension(129, 50));
        jLayeredPane1.add(lblMesAño, java.awt.BorderLayout.CENTER);

        add(jLayeredPane1, java.awt.BorderLayout.NORTH);

        slide.setBackground(new java.awt.Color(32, 32, 32));
        slide.setPreferredSize(new java.awt.Dimension(100, 100));
        add(slide, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if (month == 12) {
            month = 1;
            year++;
        } else{
            month++;
        }
        slide.show(new PanelDate(month, year), PanelSlide.AnimateType.TO_LEFT);
        showMonthYear();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if (month == 1) {
            month = 12;
            year--;
        } else{
            month--;
        }
        slide.show(new PanelDate(month, year), PanelSlide.AnimateType.TO_RIGHT);
        showMonthYear();
    }//GEN-LAST:event_btnBackActionPerformed

    private void thisMonth(){
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());
        month = calendar.get(Calendar.MONTH) +1;
        year = calendar.get(Calendar.YEAR);
    }
    
    private void showMonthYear(){
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.MONTH, month - 1);
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.DATE, 1);
        SimpleDateFormat df = new SimpleDateFormat("MMMM-yyyy");
        lblMesAño.setText(df.format(calendar.getTime()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private customizeObjects.ButtonRound btnBack;
    private customizeObjects.ButtonRound btnNext;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblMesAño;
    private customizeObjects.PanelSlide slide;
    // End of variables declaration//GEN-END:variables
}
